import { expect } from 'chai';
import { OperatorClient, VoterClient, decodeResults } from '@dorafactory/maci-sdk';
import { SimulateCosmWasmClient } from '@oraichain/cw-simulate';
import path from 'path';
import {
  createTestEnvironment,
  ContractLoader,
  DeployManager,
  AmaciContractClient,
  formatPubKeyForContract,
  formatMessageForContract,
  assertExecuteSuccess,
  log,
  assertBigIntEqual,
  advanceTime,
  queryPollId,
  getAmaciCircuitConfig,
  generateCertificateFromBigInt,
  getBackendPublicKey
} from '../src';

const amaciCircuit = getAmaciCircuitConfig();
const AMACI_E2E_TIMEOUT_MS = amaciCircuit.batchSize >= 125 ? 1_800_000 : 600_000;
const useOracleRegistration = amaciCircuit.stateTreeDepth > 4;

function buildVoteOptionMap(count: number, prefix = 'Option'): string[] {
  return Array.from({ length: count }, (_, index) => `${prefix} ${index}`);
}

/**
 * AMACI End-to-End Test (Simplified - Without Deactivate Process)
 *
 * This test demonstrates the basic AMACI voting flow:
 * 1. Environment setup
 * 2. User registration (including new key setup)
 * 3. Voting (only new key votes)
 * 4. End voting period
 * 5. Message processing
 * 6. Tallying
 * 7. Result verification
 *
 * Note: Deactivate process is not included in this test
 */

describe('AMACI End-to-End Test', function () {
  this.timeout(AMACI_E2E_TIMEOUT_MS);

  let client: SimulateCosmWasmClient;
  let operator: OperatorClient;
  let voter1: VoterClient;
  let voter2: VoterClient;
  let voter1New: VoterClient;
  let amaciContract: AmaciContractClient;
  let votingEndTime: bigint; // Store voting end time for dynamic calculation

  const adminAddress = 'dora1eu7mhp4ggxd6utnz8uzurw395natgs6jskl4ug';
  const operatorAddress = 'dora1f0cywn02dm63xl52kw8r9myu5lelxfxd7zrqan';
  const feeRecipient = 'dora1xp0twdzsdeq4qg3c64v66552deax8zmvq4zw78';

  // Unique addresses for each voter (for whitelist registration)
  const voter1Address = 'dora1x0lkxq7g7eaq2u3uh2l39yhzf5046h00w2mlsf';
  const voter2Address = 'dora17k09vurx6vr90llefe4ujxxux7hjau3y86dvyg';
  const voter1NewAddress = 'dora1qnqdcxxk385pztkyz8dphzmtknq7qe7y22l6d2';

  // Test parameters (must match selected zkey configuration)
  const stateTreeDepth = amaciCircuit.stateTreeDepth;
  const intStateTreeDepth = amaciCircuit.intStateTreeDepth;
  const voteOptionTreeDepth = amaciCircuit.voteOptionTreeDepth;
  const batchSize = amaciCircuit.batchSize;
  const maxVoteOptions = amaciCircuit.maxVoteOptions;
  const numSignUps = 3;

  // User indices
  const USER_1 = 0;
  const USER_2 = 1;
  const USER_1A = 2; // User 1's new key

  // Circuit artifacts paths (AMACI uses different zkey files from MACI)
  const circuitConfig = amaciCircuit.circuitDirName;
  const circuitDir = path.join(__dirname, '../circuits', circuitConfig);
  const processMessagesWasm = path.join(circuitDir, 'processMessages.wasm');
  const processMessagesZkey = path.join(circuitDir, 'processMessages.zkey');
  const tallyVotesWasm = path.join(circuitDir, 'tallyVotes.wasm');
  const tallyVotesZkey = path.join(circuitDir, 'tallyVotes.zkey');
  // Deactivate and AddNewKey circuits (not used in simplified test, reserved for future use)
  // const deactivateWasm = path.join(circuitDir, 'deactivate.wasm');
  // const deactivateZkey = path.join(circuitDir, 'deactivate.zkey');
  // const addNewKeyWasm = path.join(circuitDir, 'addNewKey.wasm');
  // const addNewKeyZkey = path.join(circuitDir, 'addNewKey.zkey');

  before(async () => {
    log('=== Setting up test environment ===');
    log(`Using AMACI circuit config: ${amaciCircuit.id}`);

    // Create test environment
    const env = await createTestEnvironment({
      chainId: 'amaci-test',
      bech32Prefix: 'dora'
    });

    client = env.client;

    // Fund all test addresses that are not auto-generated by createTestEnvironment
    const fundAddresses = [adminAddress, operatorAddress, feeRecipient, voter1Address, voter2Address, voter1NewAddress];
    for (const addr of fundAddresses) {
      await client.app.bank.setBalance(addr, [
        { denom: 'dora', amount: '1000000000000' },
        { denom: 'peaka', amount: '100000000000000000000000' } // 100,000 DORA in peaka
      ]);
    }

    log('Test environment created');

    // Initialize SDK clients
    operator = new OperatorClient({
      network: 'testnet',
      secretKey: 111111n
    });

    voter1 = new VoterClient({
      network: 'testnet',
      secretKey: 222222n
    });

    voter2 = new VoterClient({
      network: 'testnet',
      secretKey: 555555n
    });

    voter1New = new VoterClient({
      network: 'testnet',
      secretKey: 666666n
    });

    log('SDK clients initialized');

    // Deploy AMACI contract (need contract to get pollId)
    const contractLoader = new ContractLoader();
    const deployManager = new DeployManager(client, contractLoader);

    log('Deploying AMACI contract...');

    const coordPubKey = operator.getPubkey().toPoints();

    // Initialize app.time for cw-simulate
    const app: any = client.app;
    if (!app.time || app.time === 0) {
      app.time = Date.now() * 1e6; // Convert milliseconds to nanoseconds
      log(`Initialized app.time: ${app.time} ns`);
    }

    // Calculate voting times
    // AMACI contract requires voting period to be at least 10 minutes (600 seconds)
    // Strategy: Set minimum valid voting period (610 seconds) with start in past and end 25 seconds in future
    // Buffer time accounts for: registration(2s) + deactivate(12s) + voting(4s) + processing(5s) + margin(2s)
    const now = BigInt(app.time); // Convert to BigInt for calculation
    const startTime = now - BigInt(585) * BigInt(1_000_000_000); // 585 seconds ago
    votingEndTime = now + BigInt(25) * BigInt(1_000_000_000); // 25 seconds in the future (enough for all operations)
    // Total duration: 585 + 25 = 610 seconds (满足 600 秒最低要求)

    log(`Current time: ${now} (${new Date(Number(now / BigInt(1_000_000))).toISOString()})`);
    log(
      `Voting period: start=${startTime} (${new Date(Number(startTime / BigInt(1_000_000))).toISOString()}), end=${votingEndTime} (${new Date(Number(votingEndTime / BigInt(1_000_000))).toISOString()})`
    );
    log(`Period duration: ${(votingEndTime - startTime) / BigInt(1_000_000_000)} seconds`);
    log(`⏰ Using simulated time control - no real waiting needed`);

    const instantiateMsg = {
      parameters: {
        state_tree_depth: stateTreeDepth.toString(),
        int_state_tree_depth: intStateTreeDepth.toString(),
        vote_option_tree_depth: voteOptionTreeDepth.toString(),
        message_batch_size: batchSize.toString()
      },
      coordinator: {
        x: coordPubKey[0].toString(),
        y: coordPubKey[1].toString()
      },
      admin: adminAddress,
      fee_recipient: feeRecipient,
      operator: operatorAddress,
      voice_credit_mode: {
        unified: { amount: '100' }
      },
      registration_mode: useOracleRegistration
        ? {
            sign_up_with_oracle: {
              oracle_pubkey: getBackendPublicKey()
            }
          }
        : {
            sign_up_with_static_whitelist: {
              whitelist: {
                users: [
                  { addr: adminAddress, voice_credit_amount: null },
                  { addr: operatorAddress, voice_credit_amount: null },
                  { addr: feeRecipient, voice_credit_amount: null },
                  { addr: voter1Address, voice_credit_amount: null },
                  { addr: voter2Address, voice_credit_amount: null },
                  { addr: voter1NewAddress, voice_credit_amount: null }
                ]
              }
            }
          },
      vote_option_map: buildVoteOptionMap(maxVoteOptions),
      round_info: {
        title: 'AMACI E2E Test Round',
        description: 'Test round for AMACI e2e testing',
        link: 'https://test.example.com'
      },
      voting_time: {
        start_time: startTime.toString(),
        end_time: votingEndTime.toString()
      },
      circuit_type: '1', // QV
      certification_system: '0', // Groth16
      poll_id: 1, // Poll ID for this round (防止跨 poll 重放攻击)
      deactivate_enabled: false, // Deactivate feature disabled (default)
      // Fee config (set to 0 for e2e testing to avoid fund management in tests)
      message_fee: '0',
      deactivate_fee: '0',
      signup_fee: '0',
      // Delay config (set to 0 for fast e2e test execution)
      base_delay: 0,
      message_delay: 0,
      signup_delay: 0,
      deactivate_delay: 0
    };

    const contractInfo = await deployManager.deployAmaciContract(adminAddress, instantiateMsg);

    amaciContract = new AmaciContractClient(client, contractInfo.contractAddress, operatorAddress);

    log(`AMACI contract deployed at: ${contractInfo.contractAddress}`);

    // Query pollId from deployed contract
    const pollId = await queryPollId(amaciContract);
    log(`Poll ID retrieved from contract: ${pollId}`);

    // Initialize operator AMACI with pollId (must be after contract deployment)
    operator.initRound({
      stateTreeDepth,
      intStateTreeDepth,
      voteOptionTreeDepth,
      batchSize,
      maxVoteOptions,
      isQuadraticCost: true,
      isAmaci: true, // AMACI uses anonymous keys (d1, d2)
      pollId // From contract query
    });

    log('Operator AMACI round initialized with pollId (Quadratic Voting with anonymous keys)');
  });

  it('should complete the full AMACI voting flow', async () => {
    log('\n=== Step 1: User Registration ===\n');

    // Register user 1
    const user1PubKey = voter1.getPubkey().toPoints();
    log(`User 1 public key: [${user1PubKey[0]}, ${user1PubKey[1]}]`);

    amaciContract.setSender(voter1Address);
    const user1Certificate = useOracleRegistration
      ? generateCertificateFromBigInt(amaciContract.getContractAddress(), user1PubKey, '100')
      : undefined;
    await assertExecuteSuccess(
      () => amaciContract.signUp(formatPubKeyForContract(user1PubKey), user1Certificate),
      'User 1 sign up failed'
    );

    operator.updateStateTree(USER_1, user1PubKey, 100);
    log('User 1 registered');

    // Register user 2
    const user2PubKey = voter2.getPubkey().toPoints();
    log(`User 2 public key: [${user2PubKey[0]}, ${user2PubKey[1]}]`);

    amaciContract.setSender(voter2Address);
    const user2Certificate = useOracleRegistration
      ? generateCertificateFromBigInt(amaciContract.getContractAddress(), user2PubKey, '100')
      : undefined;
    await assertExecuteSuccess(
      () => amaciContract.signUp(formatPubKeyForContract(user2PubKey), user2Certificate),
      'User 2 sign up failed'
    );

    operator.updateStateTree(USER_2, user2PubKey, 100);
    log('User 2 registered');

    // Register user 1's new key (without deactivate process)
    const user1aPubKey = voter1New.getPubkey().toPoints();
    log(`User 1 new public key: [${user1aPubKey[0]}, ${user1aPubKey[1]}]`);

    // Register new key on chain
    amaciContract.setSender(voter1NewAddress);
    const user1aCertificate = useOracleRegistration
      ? generateCertificateFromBigInt(amaciContract.getContractAddress(), user1aPubKey, '100')
      : undefined;
    await assertExecuteSuccess(
      () => amaciContract.signUp(formatPubKeyForContract(user1aPubKey), user1aCertificate),
      'User 1 new key sign up failed'
    );

    // Add new key to operator state tree
    operator.updateStateTree(USER_1A, user1aPubKey, 100);
    log('User 1 new key registered and added to operator state tree');

    // Verify registration count
    const numSignUp = await amaciContract.getNumSignUp();
    expect(numSignUp).to.equal('3');
    log(`Total registrations: ${numSignUp}`);

    log('\n=== Step 2: Submit Votes ===\n');

    // Query pollId for building vote payloads
    const pollId = await queryPollId(amaciContract);
    log(`Using poll ID ${pollId} for vote payloads`);

    const coordPubKey = operator.getPubkey().toPoints();

    // User 1's new key votes: option 0(1), option 1(2), option 2(3)
    const vote3Payload = voter1New.buildVotePayload({
      stateIdx: USER_1A,
      operatorPubkey: coordPubKey,
      selectedOptions: [
        { idx: 0, vc: 1 },
        { idx: 1, vc: 2 },
        { idx: 2, vc: 3 }
      ],
      pollId
    });

    for (const payload of vote3Payload) {
      const message = payload.msg.map((m) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Publish vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('User 1 (new key) vote submitted');

    const msgChainLength = await amaciContract.getMsgChainLength();
    log(`Total votes submitted: ${msgChainLength}`);

    log('\n=== Step 3: End Vote Period ===\n');

    // Calculate how much time we need to advance for voting period to end
    const app: any = client.app;
    const currentTime = BigInt(app.time);
    log(
      `Current time: ${currentTime} (${new Date(Number(currentTime / BigInt(1_000_000))).toISOString()})`
    );
    log(
      `Voting end time: ${votingEndTime} (${new Date(Number(votingEndTime / BigInt(1_000_000))).toISOString()})`
    );

    if (currentTime < votingEndTime) {
      const advanceSeconds = Number((votingEndTime - currentTime) / BigInt(1_000_000_000)) + 1; // +1 second buffer
      log(`Advancing time by ${advanceSeconds} seconds to end voting period...`);
      log('⚡ Using simulated time - instant completion, no waiting!');
      await advanceTime(client, advanceSeconds);
      log(`✅ Time advanced by ${advanceSeconds} seconds, voting period has ended (simulated)`);
    } else {
      log('✅ Voting period already expired, no time advance needed!');
    }

    await assertExecuteSuccess(
      () => amaciContract.startProcessPeriod(),
      'Start process period failed'
    );

    operator.endVotePeriod();
    log('Vote period ended, processing started');

    log('\n=== Step 4: Process Messages ===\n');

    let batchCount = 0;
    while (operator.states === 1) {
      log(`Processing message batch ${batchCount}...`);

      // Generate real ZK proof using SDK
      const processResult = await operator.processMessages({
        wasmFile: processMessagesWasm,
        zkeyFile: processMessagesZkey
      });

      log(`New state commitment: ${processResult.input.newStateCommitment}`);

      if (!processResult.proof) {
        throw new Error('ProcessMessages proof is missing');
      }

      // Process on contract
      await assertExecuteSuccess(
        () =>
          amaciContract.processMessage(
            processResult.input.newStateCommitment.toString(),
            processResult.proof! // Non-null assertion after check
          ),
        `Process message batch ${batchCount} failed`
      );

      log(`Message batch ${batchCount} processed`);
      batchCount++;

      if (batchCount > 10) {
        throw new Error('Too many message processing iterations');
      }
    }

    log(`All messages processed in ${batchCount} batches`);

    // Stop processing period to transition to tallying
    await assertExecuteSuccess(
      () => amaciContract.stopProcessingPeriod(),
      'Stop processing period failed'
    );

    log('Processing period stopped, transitioning to tallying');

    log('\n=== Step 5: Tally Votes ===\n');

    let tallyCount = 0;
    while (operator.states === 2) {
      log(`Processing tally batch ${tallyCount}...`);

      // Generate real ZK proof using SDK
      const tallyResult = await operator.processTally({
        wasmFile: tallyVotesWasm,
        zkeyFile: tallyVotesZkey
      });

      log(`New tally commitment: ${tallyResult.input.newTallyCommitment}`);

      if (!tallyResult.proof) {
        throw new Error('TallyVotes proof is missing');
      }

      // Process on contract
      await assertExecuteSuccess(
        () =>
          amaciContract.processTally(
            tallyResult.input.newTallyCommitment.toString(),
            tallyResult.proof! // Non-null assertion after check
          ),
        `Process tally batch ${tallyCount} failed`
      );

      log(`Tally batch ${tallyCount} processed`);
      tallyCount++;

      if (tallyCount > 10) {
        throw new Error('Too many tally iterations');
      }
    }

    log(`Tallying completed in ${tallyCount} batches`);

    log('\n=== Step 6: Verify Results ===\n');

    const sdkResults = operator.getTallyResults();
    log('SDK results (encoded):');
    sdkResults.forEach((result, idx) => {
      log(`  Option ${idx}: ${result}`);
    });

    // Query contract results
    const contractResults = await amaciContract.getAllResults();
    log('Contract results (encoded):');
    log(JSON.stringify(contractResults, null, 2));

    // Decode results to extract vote counts and voice credits
    const decodedResults = decodeResults(contractResults);
    log('\nDecoded results:');
    decodedResults.forEach((result, index) => {
      log(`  Option ${index}: ${result.v} votes, ${result.v2} voice credits`);
    });

    // Verify results match
    expect(sdkResults.length).to.equal(maxVoteOptions);
    expect(decodedResults.length).to.equal(maxVoteOptions);

    log('\n=== Test Completed Successfully ===\n');
    log('AMACI end-to-end test passed!');
  });

  it('should query contract state correctly', async () => {
    const period = await amaciContract.getPeriod();
    log(`Contract period status: ${JSON.stringify(period)}`);

    const roundInfo = await amaciContract.getRoundInfo();
    log(`Round info: ${JSON.stringify(roundInfo)}`);

    expect(roundInfo).to.have.property('title');
  });
});

describe('AMACI Dynamic Voice Credit E2E Test', function () {
  this.timeout(AMACI_E2E_TIMEOUT_MS);

  let client: SimulateCosmWasmClient;
  let operator: OperatorClient;
  let voters: Array<{ client: VoterClient; addr: string; credits: number }>;
  let amaciContract: AmaciContractClient;
  let votingEndTime: bigint;

  const adminAddress = 'dora1eu7mhp4ggxd6utnz8uzurw395natgs6jskl4ug';
  const operatorAddress = 'dora1f0cywn02dm63xl52kw8r9myu5lelxfxd7zrqan';
  const feeRecipient = 'dora1xp0twdzsdeq4qg3c64v66552deax8zmvq4zw78';

  // Different users with different voice credits
  const lowPowerUser = 'dora1x0lkxq7g7eaq2u3uh2l39yhzf5046h00w2mlsf'; // 50 credits
  const mediumPowerUser = 'dora17k09vurx6vr90llefe4ujxxux7hjau3y86dvyg'; // 100 credits
  const highPowerUser = 'dora1qnqdcxxk385pztkyz8dphzmtknq7qe7y22l6d2'; // 200 credits

  const stateTreeDepth = amaciCircuit.stateTreeDepth;
  const intStateTreeDepth = amaciCircuit.intStateTreeDepth;
  const voteOptionTreeDepth = amaciCircuit.voteOptionTreeDepth;
  const batchSize = amaciCircuit.batchSize;
  const maxVoteOptions = amaciCircuit.maxVoteOptions;

  // Circuit artifacts paths
  const circuitConfig = amaciCircuit.circuitDirName;
  const circuitDir = path.join(__dirname, '../circuits', circuitConfig);
  const processMessagesWasm = path.join(circuitDir, 'processMessages.wasm');
  const processMessagesZkey = path.join(circuitDir, 'processMessages.zkey');
  const tallyVotesWasm = path.join(circuitDir, 'tallyVotes.wasm');
  const tallyVotesZkey = path.join(circuitDir, 'tallyVotes.zkey');

  before(async () => {
    log('\n=== Setting up AMACI Dynamic VC test environment ===');
    log(`Using AMACI circuit config: ${amaciCircuit.id}`);

    const env = await createTestEnvironment({
      chainId: 'amaci-dynamic-vc-test',
      bech32Prefix: 'dora'
    });
    client = env.client;
    log('✓ Test environment created');

    // Initialize balances
    const allAddresses = [
      adminAddress,
      operatorAddress,
      feeRecipient,
      lowPowerUser,
      mediumPowerUser,
      highPowerUser
    ];
    for (const addr of allAddresses) {
      await client.app.bank.setBalance(addr, [
        { denom: 'dora', amount: '1000000000000' },
        { denom: 'peaka', amount: '100000000000000000000000' }
      ]);
    }
    log('✓ Balances initialized');

    // Initialize operator
    operator = new OperatorClient({
      network: 'testnet',
      secretKey: 789012n
    });

    // Initialize voters
    voters = [
      {
        client: new VoterClient({ network: 'testnet', secretKey: 890123n }),
        addr: lowPowerUser,
        credits: 50
      },
      {
        client: new VoterClient({ network: 'testnet', secretKey: 901234n }),
        addr: mediumPowerUser,
        credits: 100
      },
      {
        client: new VoterClient({ network: 'testnet', secretKey: 912345n }),
        addr: highPowerUser,
        credits: 200
      }
    ];
    log(`✓ Initialized ${voters.length} voters with different voice credits`);

    // Deploy contract
    const coordPubKey = operator.getPubkey().toPoints();
    const deployManager = new DeployManager(client, new ContractLoader());

    const app: any = client.app;
    if (!app.time || app.time === 0) {
      app.time = Date.now() * 1e6;
      log(`✓ Initialized app.time: ${app.time} ns`);
    }

    const now = BigInt(app.time);
    const startTime = now - BigInt(585) * BigInt(1_000_000_000);
    votingEndTime = now + BigInt(60) * BigInt(1_000_000_000);

    const instantiateMsg = {
      parameters: {
        state_tree_depth: stateTreeDepth.toString(),
        int_state_tree_depth: intStateTreeDepth.toString(),
        vote_option_tree_depth: voteOptionTreeDepth.toString(),
        message_batch_size: batchSize.toString()
      },
      coordinator: {
        x: coordPubKey[0].toString(),
        y: coordPubKey[1].toString()
      },
      admin: adminAddress,
      fee_recipient: feeRecipient,
      operator: operatorAddress,
      // voice_credit_mode: {
      //   // dynamic: {} // ⭐ Dynamic VoiceCreditMode
      //   unified: { amount: '100' }
      // },
      voice_credit_mode: 'dynamic',
      registration_mode: useOracleRegistration
        ? {
            sign_up_with_oracle: {
              oracle_pubkey: getBackendPublicKey()
            }
          }
        : {
            sign_up_with_static_whitelist: {
              whitelist: {
                users: [
                  { addr: lowPowerUser, voice_credit_amount: '50' }, // ⭐ Different credits
                  { addr: mediumPowerUser, voice_credit_amount: '100' },
                  { addr: highPowerUser, voice_credit_amount: '200' }
                ]
              }
            }
          },
      vote_option_map: buildVoteOptionMap(maxVoteOptions, 'Dynamic Option'),
      round_info: {
        title: 'AMACI Dynamic VC Test',
        description: 'Testing dynamic voice credit allocation',
        link: 'https://test.example.com'
      },
      voting_time: {
        start_time: startTime.toString(),
        end_time: votingEndTime.toString()
      },
      circuit_type: '1',
      certification_system: '0',
      poll_id: 10, // Unique poll ID
      deactivate_enabled: false,
      // Fee config (set to 0 for e2e testing)
      message_fee: '0',
      deactivate_fee: '0',
      signup_fee: '0',
      // Delay config (set to 0 for fast e2e test execution)
      base_delay: 0,
      message_delay: 0,
      signup_delay: 0,
      deactivate_delay: 0
    };

    const contractInfo = await deployManager.deployAmaciContract(adminAddress, instantiateMsg);
    amaciContract = new AmaciContractClient(client, contractInfo.contractAddress, adminAddress);
    log(`✓ AMACI contract deployed at: ${contractInfo.contractAddress}`);

    const pollId = await queryPollId(amaciContract);
    log(`✓ Poll ID retrieved: ${pollId}`);

    operator.initRound({
      stateTreeDepth,
      intStateTreeDepth,
      voteOptionTreeDepth,
      batchSize,
      maxVoteOptions,
      isQuadraticCost: true,
      isAmaci: true,
      pollId: Number(pollId)
    });
    log('✓ Operator initialized\n');
  });

  it('should register users with different voice credits', async () => {
    log('=== Step 1: User Registration with Dynamic Voice Credits ===\n');

    for (let i = 0; i < voters.length; i++) {
      const { client: voter, addr, credits } = voters[i];
      const pubKey = voter.getPubkey().toPoints();

      amaciContract.setSender(addr);
      const certificate = useOracleRegistration
        ? generateCertificateFromBigInt(amaciContract.getContractAddress(), pubKey, credits.toString())
        : undefined;
      const oracleAmount = useOracleRegistration ? credits.toString() : undefined;
      await assertExecuteSuccess(
        () => amaciContract.signUp(formatPubKeyForContract(pubKey), certificate, oracleAmount),
        `User ${i + 1} signup failed`
      );

      operator.updateStateTree(i, pubKey, BigInt(credits), [0n, 0n, 0n, 0n]);
      log(`✓ User ${i + 1} registered: ${addr.substring(0, 20)}... with ${credits} voice credits`);
    }

    // Verify registration
    const numSignups = await amaciContract.getNumSignUp();
    expect(numSignups).to.equal(voters.length.toString());
    log(`\n✓ All ${voters.length} users registered successfully\n`);
  });

  it('should calculate voting cost based on individual voice credits', async () => {
    log('=== Step 2: Voting with Different Voice Credits ===\n');

    const pollId = await queryPollId(amaciContract);
    const coordPubKey = operator.getPubkey().toPoints();

    // User 1 (50 credits): Vote 5 times for Option A (cost: 25 credits)
    const user1 = voters[0];
    const vote1Payloads = user1.client.buildVotePayload({
      stateIdx: 0,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 0, vc: 5 }], // 5 votes for Option A
      pollId: Number(pollId)
    });

    for (const payload of vote1Payloads) {
      const message = payload.msg.map((m) => BigInt(m));
      const encPubKey = payload.encPubkeys.map((k) => BigInt(k)) as [bigint, bigint];

      amaciContract.setSender(user1.addr);
      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(encPubKey)
          ),
        'User 1 vote failed'
      );
      operator.pushMessage(message, encPubKey);
    }
    log(`✓ User 1 (50 credits): Voted 5 times for Option A (cost: 25)`);

    // User 2 (100 credits): Vote 7 times for Option B (cost: 49 credits)
    const user2 = voters[1];
    const vote2Payloads = user2.client.buildVotePayload({
      stateIdx: 1,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 1, vc: 7 }], // 7 votes for Option B
      pollId: Number(pollId)
    });

    for (const payload of vote2Payloads) {
      const message = payload.msg.map((m) => BigInt(m));
      const encPubKey = payload.encPubkeys.map((k) => BigInt(k)) as [bigint, bigint];

      amaciContract.setSender(user2.addr);
      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(encPubKey)
          ),
        'User 2 vote failed'
      );
      operator.pushMessage(message, encPubKey);
    }
    log(`✓ User 2 (100 credits): Voted 7 times for Option B (cost: 49)`);

    // User 3 (200 credits): Vote 10 times for Option C (cost: 100 credits)
    const user3 = voters[2];
    const vote3Payloads = user3.client.buildVotePayload({
      stateIdx: 2,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 2, vc: 10 }], // 10 votes for Option C
      pollId: Number(pollId)
    });

    for (const payload of vote3Payloads) {
      const message = payload.msg.map((m) => BigInt(m));
      const encPubKey = payload.encPubkeys.map((k) => BigInt(k)) as [bigint, bigint];

      amaciContract.setSender(user3.addr);
      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(encPubKey)
          ),
        'User 3 vote failed'
      );
      operator.pushMessage(message, encPubKey);
    }
    log(`✓ User 3 (200 credits): Voted 10 times for Option C (cost: 100)`);

    log('\n✓ All votes published\n');

    // End voting period
    const app: any = client.app;
    const currentTime = BigInt(app.time);

    if (currentTime < votingEndTime) {
      const advanceSeconds = Number((votingEndTime - currentTime) / BigInt(1_000_000_000)) + 1;
      log(`Advancing time by ${advanceSeconds} seconds to end voting period...`);
      await advanceTime(client, advanceSeconds);
      log(`✅ Time advanced, voting period has ended\n`);
    }

    operator.endVotePeriod();
  });

  it('should process messages after voting', async () => {
    log('=== Step 3: Processing Messages ===\n');

    // Start processing period (voting period already ended in previous test)
    amaciContract.setSender(adminAddress);
    await assertExecuteSuccess(
      () => amaciContract.startProcessPeriod(),
      'Start process period failed'
    );
    log('✓ Processing period started');

    // Process messages
    const numMessages = await amaciContract.query({ get_msg_chain_length: {} });
    log(`Processing ${numMessages} messages...`);

    let batchCount = 0;
    while (operator.states === 1) {
      log(`Processing message batch ${batchCount}...`);

      const processResult = await operator.processMessages({
        wasmFile: processMessagesWasm,
        zkeyFile: processMessagesZkey
      });

      if (!processResult.proof) {
        throw new Error('ProcessMessages proof is missing');
      }

      await assertExecuteSuccess(
        () =>
          amaciContract.processMessage(
            processResult.input.newStateCommitment.toString(),
            processResult.proof!
          ),
        `Process message batch ${batchCount} failed`
      );

      log(`Message batch ${batchCount} processed`);
      batchCount++;

      if (batchCount > 10) {
        throw new Error('Too many message processing iterations');
      }
    }
    log(`✓ All messages processed in ${batchCount} batches\n`);

    // Stop processing period
    await assertExecuteSuccess(
      () => amaciContract.stopProcessingPeriod(),
      'Stop processing period failed'
    );
    log('✓ Processing period stopped\n');

    // Note: In MACI protocol, actual balances after voting are maintained in the state tree
    // The operator SDK tracks the current state. The chain only stores initial balances and state commitments.
    log('✓ Messages processed successfully, proceeding to tally\n');
  });

  it('should verify tally results reflect dynamic weights', async () => {
    log('=== Step 4: Tallying Votes ===\n');

    // Processing period already stopped in previous test
    amaciContract.setSender(adminAddress);

    // Process tally
    let tallyCount = 0;
    while (operator.states === 2) {
      log(`Processing tally batch ${tallyCount}...`);

      const tallyResult = await operator.processTally({
        wasmFile: tallyVotesWasm,
        zkeyFile: tallyVotesZkey
      });

      if (!tallyResult.proof) {
        throw new Error('TallyVotes proof is missing');
      }

      await assertExecuteSuccess(
        () =>
          amaciContract.processTally(
            tallyResult.input.newTallyCommitment.toString(),
            tallyResult.proof!
          ),
        `Process tally batch ${tallyCount} failed`
      );

      log(`Tally batch ${tallyCount} processed`);
      tallyCount++;

      if (tallyCount > 10) {
        throw new Error('Too many tally iterations');
      }
    }
    log(`✓ Tallying completed in ${tallyCount} batches\n`);

    // Stop tallying period and get results
    const tallyResults = operator.getTallyResults();

    await assertExecuteSuccess(
      () =>
        amaciContract.stopTallyingPeriod(
          tallyResults.map((r) => r.toString()),
          operator.tallySalt.toString()
        ),
      'Stop tallying period failed'
    );
    log('✓ Tallying period stopped\n');

    // Query and verify results
    const contractResults = await amaciContract.getAllResults();
    log('\n=== Tally Results ===');
    log(JSON.stringify(contractResults, null, 2));

    // Decode results to extract vote counts and voice credits
    const decodedResults = decodeResults(contractResults);
    log('\n=== Decoded Results ===');
    decodedResults.forEach((result, index) => {
      log(`Option ${index}: ${result.v} votes, ${result.v2} voice credits`);
    });

    // Verify results match expected values
    // User 1: 5 votes for Option A (cost: 25 credits)
    // User 2: 7 votes for Option B (cost: 49 credits)
    // User 3: 10 votes for Option C (cost: 100 credits)
    assertBigIntEqual(BigInt(decodedResults[0].v), 5n, 'Option A votes');
    assertBigIntEqual(BigInt(decodedResults[0].v2), 25n, 'Option A voice credits');

    assertBigIntEqual(BigInt(decodedResults[1].v), 7n, 'Option B votes');
    assertBigIntEqual(BigInt(decodedResults[1].v2), 49n, 'Option B voice credits');

    assertBigIntEqual(BigInt(decodedResults[2].v), 10n, 'Option C votes');
    assertBigIntEqual(BigInt(decodedResults[2].v2), 100n, 'Option C voice credits');

    assertBigIntEqual(BigInt(decodedResults[3].v), 0n, 'Option D votes');
    assertBigIntEqual(BigInt(decodedResults[3].v2), 0n, 'Option D voice credits');

    assertBigIntEqual(BigInt(decodedResults[4].v), 0n, 'Option E votes');
    assertBigIntEqual(BigInt(decodedResults[4].v2), 0n, 'Option E voice credits');

    log('\nAll tally results verified');
    log('AMACI Dynamic VC Test Completed Successfully\n');
  });
});
