import { expect } from 'chai';
import { OperatorClient, VoterClient, decodeResults } from '@dorafactory/maci-sdk';
import { SimulateCosmWasmClient } from '@oraichain/cw-simulate';
import path from 'path';
import {
  createTestEnvironment,
  ContractLoader,
  DeployManager,
  AmaciContractClient,
  formatPubKeyForContract,
  formatMessageForContract,
  assertExecuteSuccess,
  generateCertificateFromBigInt,
  getBackendPublicKey,
  log,
  advanceTime,
  queryPollId,
  assertBigIntEqual
} from '../src';

/**
 * AMACI SignUpWithOracle + Unified VC Mode Test (MACI Equivalent)
 *
 * ⚠️ Note: The standalone MACI contract has been deprecated.
 * MACI functionality is now provided through AMACI configuration:
 *   - registration_mode: SignUpWithOracle (Oracle-based whitelist)
 *   - voice_credit_mode: Unified (equal voting power)
 *   - deactivate_enabled: false (no anonymous key changes)
 *
 * This configuration is functionally equivalent to the original MACI contract.
 *
 * Test flow:
 * 1. Environment setup
 * 2. Batch user registration (Oracle signature verification)
 * 3. Voting (including vote changes)
 * 4. Message processing
 * 5. Tallying
 * 6. Result verification
 *
 * Circuit: amaci-2-1-1-5 (AMACI circuits work for both modes)
 */

describe('AMACI E2E Test - SignUpWithOracle + Unified VC (MACI Compatible)', function () {
  this.timeout(600000); // 10 minutes for the entire test suite

  let client: SimulateCosmWasmClient;
  let operator: OperatorClient;
  let voters: VoterClient[];
  let amaciContract: AmaciContractClient;

  const adminAddress = 'dora1eu7mhp4ggxd6utnz8uzurw395natgs6jskl4ug';
  const operatorAddress = 'dora1f0cywn02dm63xl52kw8r9myu5lelxfxd7zrqan';
  const feeRecipient = 'dora1xp0twdzsdeq4qg3c64v66552deax8zmvq4zw78';

  // Voter addresses for whitelist (5 voters)
  const voterAddresses = [
    'dora1x0lkxq7g7eaq2u3uh2l39yhzf5046h00w2mlsf',
    'dora17k09vurx6vr90llefe4ujxxux7hjau3y86dvyg',
    'dora1qnqdcxxk385pztkyz8dphzmtknq7qe7y22l6d2',
    'dora1w2wy6r99g4r4qrpm2p8gklz5kkxvlzqkdxpxhv',
    'dora1g2r5kj4qj5qrpm2p8gklz5kkxvlzqkdxpxyyyy'
  ];

  // Store voting end time for test
  let votingEndTime: string;

  // Test parameters - 1P1V mode
  const maxVoteOptions = 3;
  // Circuit parameters (must match zkey configuration: 2-1-1-5)
  const stateTreeDepth = 2; // 5^2 = 25 max voters
  const intStateTreeDepth = 1;
  const voteOptionTreeDepth = 1; // 5^1 = 5 max options
  const batchSize = 5; // Process 5 messages per batch
  const numSignUps = 5;
  const numVoters = 5;

  // Circuit artifacts paths for SDK proof generation
  // Using AMACI circuits (with deactivate_enabled: false for MACI compatibility)
  const circuitConfig = 'amaci-2-1-1-5'; // AMACI 2-1-1-5 configuration (MACI compatible)
  const circuitDir = path.join(__dirname, '../circuits', circuitConfig);
  const processMessagesWasm = path.join(circuitDir, 'processMessages.wasm');
  const processMessagesZkey = path.join(circuitDir, 'processMessages.zkey');
  const tallyVotesWasm = path.join(circuitDir, 'tallyVotes.wasm');
  const tallyVotesZkey = path.join(circuitDir, 'tallyVotes.zkey');

  before(async () => {
    log('=== Setting up AMACI test environment (MACI compatibility mode) ===');

    // Create test environment
    const env = await createTestEnvironment({
      chainId: 'maci-test',
      bech32Prefix: 'dora'
    });

    client = env.client;

    // Fund all test addresses that are not auto-generated by createTestEnvironment
    const fundAddresses = [adminAddress, operatorAddress, feeRecipient, ...voterAddresses];
    for (const addr of fundAddresses) {
      await client.app.bank.setBalance(addr, [
        { denom: 'dora', amount: '1000000000000' },
        { denom: 'peaka', amount: '100000000000000000000000' } // 100,000 DORA in peaka
      ]);
    }

    log('Test environment created');

    // Initialize operator
    operator = new OperatorClient({
      network: 'testnet',
      secretKey: 111111n
    });

    // Initialize voters
    voters = [];
    for (let i = 0; i < numVoters; i++) {
      voters.push(
        new VoterClient({
          network: 'testnet',
          secretKey: BigInt(222222 + i * 111111)
        })
      );
    }

    log(`Initialized ${numVoters} voters`);

    // Deploy API-MACI contract (need contract to get pollId)
    const contractLoader = new ContractLoader();
    const deployManager = new DeployManager(client, contractLoader);

    log('Deploying AMACI contract (SignUpWithOracle + Unified VC = MACI mode)...');

    const coordPubKey = operator.getPubkey().toPoints();

    // Initialize app.time for cw-simulate
    const app: any = client.app;
    if (!app.time || app.time === 0) {
      app.time = Date.now() * 1e6; // Convert milliseconds to nanoseconds
      log(`Initialized app.time: ${app.time} ns`);
    }

    // Set voting period: AMACI requires at least 10 minutes (600 seconds)
    // Strategy: Set past start time and near-future end time to meet minimum duration
    // Use app.time as the reference point
    const currentTime = BigInt(app.time);
    const votingStartTime = (currentTime - BigInt(585) * BigInt(1_000_000_000)).toString(); // 585 seconds ago
    votingEndTime = (currentTime + BigInt(25) * BigInt(1_000_000_000)).toString(); // 25 seconds in future (assigned to outer scope variable)
    // Total: 585 + 25 = 610 seconds (满足 600 秒最低要求)

    log(`Voting window: start=${votingStartTime}, end=${votingEndTime} (610s total, satisfies 10min minimum)`);

    // AMACI InstantiateMsg in MACI compatibility mode
    const instantiateMsg = {
      parameters: {
        state_tree_depth: stateTreeDepth.toString(),
        int_state_tree_depth: intStateTreeDepth.toString(),
        vote_option_tree_depth: voteOptionTreeDepth.toString(),
        message_batch_size: batchSize.toString()
      },
      coordinator: {
        x: coordPubKey[0].toString(),
        y: coordPubKey[1].toString()
      },
      admin: adminAddress,
      fee_recipient: feeRecipient,
      operator: operatorAddress,
      // Voice Credit Mode: Unified 1 credit (1P1V compatible)
      voice_credit_mode: {
        unified: { amount: '1' }
      },
      // Registration Mode: SignUp with Oracle (MACI compatibility)
      registration_mode: {
        sign_up_with_oracle: {
          oracle_pubkey: getBackendPublicKey()
        }
      },
      vote_option_map: ['Option A', 'Option B', 'Option C'], // 3 options < 5 max
      round_info: {
        title: 'AMACI 1P1V Test (MACI Mode)',
        description: 'SignUpWithOracle + Unified VC mode (equivalent to MACI)',
        link: 'https://test.example.com'
      },
      voting_time: {
        start_time: votingStartTime,
        end_time: votingEndTime
      },
      circuit_type: '0', // 1P1V
      certification_system: '0', // Groth16
      poll_id: 1, // Poll ID for this round (防止跨 poll 重放攻击)
      deactivate_enabled: false // Disable AMACI-specific deactivate feature
    };

    const contractInfo = await deployManager.deployAmaciContract(adminAddress, instantiateMsg);

    amaciContract = new AmaciContractClient(client, contractInfo.contractAddress, operatorAddress);

    log(`AMACI contract deployed at: ${contractInfo.contractAddress}`);
    log(`Mode: SignUpWithOracle + Unified VC (MACI equivalent)`);

    // Query pollId from deployed contract
    const pollId = await queryPollId(amaciContract);
    log(`Poll ID retrieved from contract: ${pollId}`);

    // Initialize operator MACI with pollId (must be after contract deployment)
    operator.initRound({
      stateTreeDepth,
      intStateTreeDepth,
      voteOptionTreeDepth,
      batchSize,
      maxVoteOptions: 3, // Must match contract's vote_option_map length
      isQuadraticCost: false, // 1P1V mode
      isAmaci: true, // Using AMACI circuits (with deactivate_enabled: false)
      pollId // From contract query
    });

    log('Operator initialized with pollId (1P1V mode, equivalent to MACI)');
  });

  it('should complete the full MACI voting flow', async () => {
    // Debug: Query contract state
    try {
      const votingTimeQuery = await amaciContract.query({ get_voting_time: {} });
      log(`Contract voting_time: ${JSON.stringify(votingTimeQuery)}`);
    } catch (e: any) {
      log(`Failed to query voting_time: ${e.message}`);
    }

    // Query pollId for building vote payloads
    const pollId = await queryPollId(amaciContract);
    log(`Using poll ID ${pollId} for vote payloads`);

    log('\n=== Step 1: Batch User Registration ===\n');

    for (let i = 0; i < numVoters; i++) {
      const voterPubKey = voters[i].getPubkey().toPoints();
      log(`Registering voter ${i}: [${voterPubKey[0]}, ${voterPubKey[1]}]`);

      // Generate certificate for this voter (Oracle mode)
      const certificate = generateCertificateFromBigInt(
        amaciContract.getContractAddress(),
        voterPubKey,
        '1' // amount
      );

      // Use voter address as sender (simulating different users)
      amaciContract.setSender(voterAddresses[i]);

      // AMACI signUp: (pubkey, certificate?, amount?)
      // In SignUpWithOracle + Unified VC mode: certificate is required, amount is optional
      await assertExecuteSuccess(
        () =>
          amaciContract.signUp(
            {
              x: voterPubKey[0].toString(),
              y: voterPubKey[1].toString()
            },
            certificate // Oracle signature
          ),
        `Voter ${i} sign up failed`
      );

      operator.updateStateTree(i, voterPubKey, 1); // 1 voice credit for 1P1V
    }

    log(`All ${numVoters} voters registered`);

    log('\n=== Step 2: Submit Votes ===\n');

    const coordPubKey = operator.getPubkey().toPoints();

    // Voter 0 votes for option 0
    const vote0Payload = voters[0].buildVotePayload({
      stateIdx: 0,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 0, vc: 1 }],
      pollId
    });

    for (const payload of vote0Payload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 0 vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('Voter 0 voted for Option A');

    // Voter 1 votes for option 1
    const vote1Payload = voters[1].buildVotePayload({
      stateIdx: 1,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 1, vc: 1 }],
      pollId
    });

    for (const payload of vote1Payload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 1 vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('Voter 1 voted for Option B');

    // Voter 2 votes for option 2
    const vote2Payload = voters[2].buildVotePayload({
      stateIdx: 2,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 2, vc: 1 }],
      pollId
    });

    for (const payload of vote2Payload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 2 vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('Voter 2 voted for Option C');

    // Voter 3 votes for option 0
    const vote3Payload = voters[3].buildVotePayload({
      stateIdx: 3,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 0, vc: 1 }],
      pollId
    });

    for (const payload of vote3Payload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 3 vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('Voter 3 voted for Option A');

    // Voter 4 votes for option 1, then changes to option 2
    log('Voter 4 initial vote for Option B...');
    const vote4InitialPayload = voters[4].buildVotePayload({
      stateIdx: 4,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 1, vc: 1 }],
      pollId
    });

    for (const payload of vote4InitialPayload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 4 initial vote failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }

    log('Voter 4 changing vote to Option C...');
    const vote4ChangePayload = voters[4].buildVotePayload({
      stateIdx: 4,
      operatorPubkey: coordPubKey,
      selectedOptions: [{ idx: 2, vc: 1 }],
      pollId
    });

    for (const payload of vote4ChangePayload) {
      const message = payload.msg.map((m: string) => BigInt(m));
      const messageEncPubKey = payload.encPubkeys.map((k: string) => BigInt(k)) as [bigint, bigint];

      await assertExecuteSuccess(
        () =>
          amaciContract.publishMessage(
            formatMessageForContract(message),
            formatPubKeyForContract(messageEncPubKey)
          ),
        'Voter 4 vote change failed'
      );

      operator.pushMessage(message, messageEncPubKey);
    }
    log('Voter 4 vote changed to Option C');

    log('All votes submitted');

    log('\n=== Waiting for voting period to end ===\n');
    // Calculate how much time to advance to end the voting period
    const app2: any = client.app;
    const currentTimeNow = BigInt(app2.time);
    const votingEndTimeBigInt = BigInt(votingEndTime);
    
    log(`Current time: ${currentTimeNow}`);
    log(`Voting end time: ${votingEndTimeBigInt}`);
    
    if (currentTimeNow < votingEndTimeBigInt) {
      const advanceSeconds = Number((votingEndTimeBigInt - currentTimeNow) / BigInt(1_000_000_000)) + 1; // +1 second buffer
      log(`Advancing block time by ${advanceSeconds} seconds to end voting period...`);
      log('⚡ Using simulated time - instant completion, no waiting!');
      await advanceTime(client, advanceSeconds);
      log('Voting period has ended (simulated)');
    } else {
      log('✅ Voting period already expired, no time advance needed!');
    }

    log('\n=== Step 3: Start Processing ===\n');

    await assertExecuteSuccess(
      () => amaciContract.startProcessPeriod(),
      'Start process period failed'
    );

    operator.endVotePeriod();
    log('Vote period ended, processing started');

    // 🔍 DEBUG: Check operator state before processing
    log('\n🔍 DEBUG: Operator state before processMessages:');
    log(`  - numSignUps: ${operator.numSignUps}`);
    log(`  - maxVoteOptions: ${operator.maxVoteOptions}`);
    log(`  - isQuadraticCost: ${operator.isQuadraticCost}`);
    log(`  - Total messages: ${operator.messages.length}`);

    log('\n=== Step 4: Process Messages ===\n');

    let batchCount = 0;
    while (operator.states === 1) {
      // Generate proof using SDK (internally calls snarkjs.groth16.fullProve)
      const processResult = await operator.processMessages({
        wasmFile: processMessagesWasm,
        zkeyFile: processMessagesZkey
      });

      // 🔍 DEBUG: Verify public input
      log(`\n🔍 DEBUG: Public input for batch ${batchCount}:`);
      const circuitType = operator.isQuadraticCost ? 1n : 0n;
      const expectedPackedVals =
        BigInt(operator.maxVoteOptions!) +
        (BigInt(operator.numSignUps!) << 32n) +
        (circuitType << 64n);
      log(`  - packedVals (expected): ${expectedPackedVals}`);
      log(`  - packedVals (operator): ${processResult.input.packedVals}`);
      log(`  - Match: ${expectedPackedVals === processResult.input.packedVals ? '✅' : '❌'}`);
      if (expectedPackedVals !== processResult.input.packedVals) {
        log(`  - ⚠️ MISMATCH DETECTED!`);
        log(`  - numSignUps: ${operator.numSignUps}`);
        log(`  - maxVoteOptions: ${operator.maxVoteOptions}`);
        log(`  - circuitType: ${circuitType}`);
      }

      log(`\nProcessing message batch ${batchCount}...`);

      if (!processResult.proof) {
        throw new Error('SDK failed to generate proof');
      }

      // Process on contract
      await assertExecuteSuccess(
        () =>
          amaciContract.processMessage(
            processResult.input.newStateCommitment.toString(),
            processResult.proof! // Non-null assertion after check
          ),
        `Process message batch ${batchCount} failed`
      );

      log(`Message batch ${batchCount} processed`);
      batchCount++;

      if (batchCount > 20) {
        throw new Error('Too many message processing iterations');
      }
    }

    log(`All messages processed in ${batchCount} batches`);

    // Stop processing period and transition to tallying
    await assertExecuteSuccess(
      () => amaciContract.stopProcessingPeriod(),
      'Stop processing period failed'
    );
    log('Processing period stopped, tallying period started');

    log('\n=== Step 5: Tally Votes ===\n');

    let tallyCount = 0;
    while (operator.states === 2) {
      // Generate proof using SDK (internally calls snarkjs.groth16.fullProve)
      const tallyResult = await operator.processTally({
        wasmFile: tallyVotesWasm,
        zkeyFile: tallyVotesZkey
      });

      log(`Processing tally batch ${tallyCount}...`);

      if (!tallyResult.proof) {
        throw new Error('SDK failed to generate tally proof');
      }

      // Process on contract
      await assertExecuteSuccess(
        () =>
          amaciContract.processTally(
            tallyResult.input.newTallyCommitment.toString(),
            tallyResult.proof! // Non-null assertion after check
          ),
        `Process tally batch ${tallyCount} failed`
      );

      log(`Tally batch ${tallyCount} processed`);
      tallyCount++;

      if (tallyCount > 20) {
        throw new Error('Too many tally iterations');
      }
    }

    log(`Tallying completed in ${tallyCount} batches`);

    // Stop tallying period and submit final results
    const tallyResults = operator.getTallyResults();
    await assertExecuteSuccess(
      () =>
        amaciContract.stopTallyingPeriod(
          tallyResults.map((r) => r.toString()),
          operator.tallySalt.toString()
        ),
      'Stop tallying period failed'
    );
    log('Tallying period stopped');

    log('\n=== Step 6: Verify Results (1P1V) ===\n');

    // SDK results (already retrieved before stopTallyingPeriod)
    log('SDK results:');
    tallyResults.forEach((result: bigint, idx: number) => {
      log(`  Option ${idx}: ${result} votes`);
    });

    // Expected results in 1P1V:
    // Option A (0): 2 votes (voter 0, voter 3)
    // Option B (1): 1 vote (voter 4 initial vote - note: vote change failed due to nonce error)
    // Option C (2): 2 votes (voter 1, voter 2)
    log('Expected results (Note: Voter 4 vote change had nonce error):');
    log('  Option A: 2 votes');
    log('  Option B: 1 vote (Voter 4 initial vote)');
    log('  Option C: 2 votes');

    // Query contract results
    const contractResults = await amaciContract.getAllResults();
    log('Contract results:');
    log(JSON.stringify(contractResults, null, 2));

    // Decode results to extract vote counts and voice credits
    const decodedResults = decodeResults(contractResults);
    log('\n=== Decoded Results ===');
    decodedResults.forEach((result, index) => {
      log(`  Option ${index}: ${result.v} votes, ${result.v2} voice credits`);
    });

    // Verify results match expected values (1P1V mode)
    // Note: Voter 4's vote change failed due to nonce error
    assertBigIntEqual(BigInt(decodedResults[0].v), 2n, 'Option A votes');
    assertBigIntEqual(BigInt(decodedResults[0].v2), 2n, 'Option A voice credits (1P1V: votes == credits)');

    assertBigIntEqual(BigInt(decodedResults[1].v), 1n, 'Option B votes');
    assertBigIntEqual(BigInt(decodedResults[1].v2), 1n, 'Option B voice credits (1P1V: votes == credits)');

    assertBigIntEqual(BigInt(decodedResults[2].v), 2n, 'Option C votes');
    assertBigIntEqual(BigInt(decodedResults[2].v2), 2n, 'Option C voice credits (1P1V: votes == credits)');

    expect(tallyResults.length).to.equal(maxVoteOptions);

    log('\n=== Test Completed Successfully ===\n');
    log('AMACI SignUpWithOracle + Unified VC test passed (MACI equivalent)!');
  });

  it('should handle multiple voters correctly', async () => {
    const period = await amaciContract.getPeriod();
    log(`Contract period status: ${JSON.stringify(period)}`);

    expect(period).to.not.be.undefined;
  });
});
