/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  admin: Addr;
  denom: string;
  maci_code_id: number;
  registry_contract: Addr;
  treasury_manager: Addr;
}
export type ExecuteMsg = {
  update_config: {
    admin?: Addr | null;
    denom?: string | null;
  };
} | {
  update_maci_code_id: {
    code_id: number;
  };
} | {
  update_amaci_registry_contract: {
    registry_contract: Addr;
  };
} | {
  add_operator: {
    operator: Addr;
  };
} | {
  remove_operator: {
    operator: Addr;
  };
} | {
  deposit: {};
} | {
  withdraw: {
    amount: Uint128;
    recipient?: Addr | null;
  };
} | {
  create_api_maci_round: {
    certification_system: Uint256;
    circuit_type: Uint256;
    coordinator: PubKey;
    end_time: Timestamp;
    max_voters: number;
    round_info: RoundInfo;
    start_time: Timestamp;
    vote_option_map: string[];
    whitelist_backend_pubkey: string;
  };
} | {
  set_round_info: {
    contract_addr: string;
    round_info: RoundInfo;
  };
} | {
  set_vote_options_map: {
    contract_addr: string;
    vote_option_map: string[];
  };
};
export type Uint128 = string;
export type Uint256 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface PubKey {
  x: Uint256;
  y: Uint256;
}
export interface RoundInfo {
  description: string;
  link: string;
  title: string;
}
export type QueryMsg = {
  config: {};
} | {
  operators: {};
} | {
  is_operator: {
    address: Addr;
  };
} | {
  balance: {};
} | {
  maci_code_id: {};
} | {
  treasury_manager: {};
};
export interface Config {
  admin: Addr;
  denom: string;
}
export type Boolean = boolean;
export type ArrayOfOperatorInfo = OperatorInfo[];
export interface OperatorInfo {
  added_at: Timestamp;
  address: Addr;
}