/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Addr = string;
export interface InstantiateMsg {
  admin: Addr;
  denom: string;
  oracle_maci_code_id: number;
  registry_contract?: Addr | null;
}
export type ExecuteMsg =
  | {
      update_config: {
        admin?: Addr | null;
        denom?: string | null;
        registry_contract?: Addr | null;
      };
    }
  | {
      add_operator: {
        operator: Addr;
      };
    }
  | {
      remove_operator: {
        operator: Addr;
      };
    }
  | {
      deposit: {};
    }
  | {
      withdraw: {
        amount: Uint128;
        recipient?: Addr | null;
      };
    }
  | {
      update_oracle_maci_code_id: {
        code_id: number;
      };
    }
  | {
      create_oracle_maci_round: {
        certification_system: Uint256;
        circuit_type: Uint256;
        coordinator: PubKey;
        end_time: Timestamp;
        max_voters: number;
        round_info: RoundInfo;
        start_time: Timestamp;
        vote_option_map: string[];
        whitelist_backend_pubkey: string;
      };
    }
  | {
      set_round_info: {
        contract_addr: string;
        round_info: RoundInfo;
      };
    }
  | {
      set_vote_options_map: {
        contract_addr: string;
        vote_option_map: string[];
      };
    }
  | {
      grant_to_voter: {
        base_amount: Uint128;
        contract_addr: string;
        grantee: Addr;
      };
    };
export type Uint128 = string;
export type Uint256 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface PubKey {
  x: Uint256;
  y: Uint256;
}
export interface RoundInfo {
  description: string;
  link: string;
  title: string;
}
export type QueryMsg =
  | {
      config: {};
    }
  | {
      operators: {};
    }
  | {
      is_operator: {
        address: Addr;
      };
    }
  | {
      balance: {};
    }
  | {
      maci_contracts: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      operator_maci_contracts: {
        limit?: number | null;
        operator: Addr;
        start_after?: number | null;
      };
    }
  | {
      maci_contract: {
        contract_id: number;
      };
    }
  | {
      oracle_maci_code_id: {};
    };
export interface Config {
  admin: Addr;
  denom: string;
  registry_contract?: Addr | null;
}
export type Boolean = boolean;
export type NullableMaciContractInfo = MaciContractInfo | null;
export interface MaciContractInfo {
  code_id: number;
  contract_address: Addr;
  created_at: Timestamp;
  creation_fee: Uint128;
  creator_operator: Addr;
  round_title: string;
}
export type ArrayOfMaciContractInfo = MaciContractInfo[];
export type ArrayOfOperatorInfo = OperatorInfo[];
export interface OperatorInfo {
  added_at: Timestamp;
  address: Addr;
}
