/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import {
  CosmWasmClient,
  SigningCosmWasmClient,
  ExecuteResult,
} from '@cosmjs/cosmwasm-stargate';
import { Coin, StdFee } from '@cosmjs/amino';
import {
  Addr,
  InstantiateMsg,
  ExecuteMsg,
  Uint128,
  Uint256,
  Timestamp,
  Uint64,
  PubKey,
  RoundInfo,
  QueryMsg,
  Config,
  Boolean,
  NullableMaciContractInfo,
  MaciContractInfo,
  ArrayOfMaciContractInfo,
  ArrayOfOperatorInfo,
  OperatorInfo,
} from './Saas.types';
export interface SaasReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  operators: () => Promise<ArrayOfOperatorInfo>;
  isOperator: ({ address }: { address: Addr }) => Promise<Boolean>;
  balance: () => Promise<Uint128>;
  maciContracts: ({
    limit,
    startAfter,
  }: {
    limit?: number;
    startAfter?: number;
  }) => Promise<ArrayOfMaciContractInfo>;
  operatorMaciContracts: ({
    limit,
    operator,
    startAfter,
  }: {
    limit?: number;
    operator: Addr;
    startAfter?: number;
  }) => Promise<ArrayOfMaciContractInfo>;
  maciContract: ({
    contractId,
  }: {
    contractId: number;
  }) => Promise<NullableMaciContractInfo>;
  oracleMaciCodeId: () => Promise<Uint64>;
}
export class SaasQueryClient implements SaasReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.operators = this.operators.bind(this);
    this.isOperator = this.isOperator.bind(this);
    this.balance = this.balance.bind(this);
    this.maciContracts = this.maciContracts.bind(this);
    this.operatorMaciContracts = this.operatorMaciContracts.bind(this);
    this.maciContract = this.maciContract.bind(this);
    this.oracleMaciCodeId = this.oracleMaciCodeId.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {},
    });
  };
  operators = async (): Promise<ArrayOfOperatorInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operators: {},
    });
  };
  isOperator = async ({ address }: { address: Addr }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_operator: {
        address,
      },
    });
  };
  balance = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {},
    });
  };
  maciContracts = async ({
    limit,
    startAfter,
  }: {
    limit?: number;
    startAfter?: number;
  }): Promise<ArrayOfMaciContractInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      maci_contracts: {
        limit,
        start_after: startAfter,
      },
    });
  };
  operatorMaciContracts = async ({
    limit,
    operator,
    startAfter,
  }: {
    limit?: number;
    operator: Addr;
    startAfter?: number;
  }): Promise<ArrayOfMaciContractInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operator_maci_contracts: {
        limit,
        operator,
        start_after: startAfter,
      },
    });
  };
  maciContract = async ({
    contractId,
  }: {
    contractId: number;
  }): Promise<NullableMaciContractInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      maci_contract: {
        contract_id: contractId,
      },
    });
  };
  oracleMaciCodeId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      oracle_maci_code_id: {},
    });
  };
}
export interface SaasInterface extends SaasReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateConfig: (
    {
      admin,
      denom,
      registryContract,
    }: {
      admin?: Addr;
      denom?: string;
      registryContract?: Addr;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  addOperator: (
    {
      operator,
    }: {
      operator: Addr;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  removeOperator: (
    {
      operator,
    }: {
      operator: Addr;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  deposit: (
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  withdraw: (
    {
      amount,
      recipient,
    }: {
      amount: Uint128;
      recipient?: Addr;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  updateOracleMaciCodeId: (
    {
      codeId,
    }: {
      codeId: number;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  createOracleMaciRound: (
    {
      certificationSystem,
      circuitType,
      coordinator,
      endTime,
      maxVoters,
      roundInfo,
      startTime,
      voteOptionMap,
      whitelistBackendPubkey,
    }: {
      certificationSystem: Uint256;
      circuitType: Uint256;
      coordinator: PubKey;
      endTime: Timestamp;
      maxVoters: number;
      roundInfo: RoundInfo;
      startTime: Timestamp;
      voteOptionMap: string[];
      whitelistBackendPubkey: string;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  setRoundInfo: (
    {
      contractAddr,
      roundInfo,
    }: {
      contractAddr: string;
      roundInfo: RoundInfo;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  setVoteOptionsMap: (
    {
      contractAddr,
      voteOptionMap,
    }: {
      contractAddr: string;
      voteOptionMap: string[];
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
  grantToVoter: (
    {
      baseAmount,
      contractAddr,
      grantee,
    }: {
      baseAmount: Uint128;
      contractAddr: string;
      grantee: Addr;
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[]
  ) => Promise<ExecuteResult>;
}
export class SaasClient extends SaasQueryClient implements SaasInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(
    client: SigningCosmWasmClient,
    sender: string,
    contractAddress: string
  ) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.addOperator = this.addOperator.bind(this);
    this.removeOperator = this.removeOperator.bind(this);
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.updateOracleMaciCodeId = this.updateOracleMaciCodeId.bind(this);
    this.createOracleMaciRound = this.createOracleMaciRound.bind(this);
    this.setRoundInfo = this.setRoundInfo.bind(this);
    this.setVoteOptionsMap = this.setVoteOptionsMap.bind(this);
    this.grantToVoter = this.grantToVoter.bind(this);
  }
  updateConfig = async (
    {
      admin,
      denom,
      registryContract,
    }: {
      admin?: Addr;
      denom?: string;
      registryContract?: Addr;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_config: {
          admin,
          denom,
          registry_contract: registryContract,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  addOperator = async (
    {
      operator,
    }: {
      operator: Addr;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        add_operator: {
          operator,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  removeOperator = async (
    {
      operator,
    }: {
      operator: Addr;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        remove_operator: {
          operator,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  deposit = async (
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        deposit: {},
      },
      fee,
      memo,
      _funds
    );
  };
  withdraw = async (
    {
      amount,
      recipient,
    }: {
      amount: Uint128;
      recipient?: Addr;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        withdraw: {
          amount,
          recipient,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  updateOracleMaciCodeId = async (
    {
      codeId,
    }: {
      codeId: number;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_oracle_maci_code_id: {
          code_id: codeId,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  createOracleMaciRound = async (
    {
      certificationSystem,
      circuitType,
      coordinator,
      endTime,
      maxVoters,
      roundInfo,
      startTime,
      voteOptionMap,
      whitelistBackendPubkey,
    }: {
      certificationSystem: Uint256;
      circuitType: Uint256;
      coordinator: PubKey;
      endTime: Timestamp;
      maxVoters: number;
      roundInfo: RoundInfo;
      startTime: Timestamp;
      voteOptionMap: string[];
      whitelistBackendPubkey: string;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        create_oracle_maci_round: {
          certification_system: certificationSystem,
          circuit_type: circuitType,
          coordinator,
          end_time: endTime,
          max_voters: maxVoters.toString(),
          round_info: roundInfo,
          start_time: startTime,
          vote_option_map: voteOptionMap,
          whitelist_backend_pubkey: whitelistBackendPubkey,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  setRoundInfo = async (
    {
      contractAddr,
      roundInfo,
    }: {
      contractAddr: string;
      roundInfo: RoundInfo;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        set_round_info: {
          contract_addr: contractAddr,
          round_info: roundInfo,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  setVoteOptionsMap = async (
    {
      contractAddr,
      voteOptionMap,
    }: {
      contractAddr: string;
      voteOptionMap: string[];
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        set_vote_options_map: {
          contract_addr: contractAddr,
          vote_option_map: voteOptionMap,
        },
      },
      fee,
      memo,
      _funds
    );
  };
  grantToVoter = async (
    {
      baseAmount,
      contractAddr,
      grantee,
    }: {
      baseAmount: Uint128;
      contractAddr: string;
      grantee: Addr;
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[]
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        grant_to_voter: {
          base_amount: baseAmount,
          contract_addr: contractAddr,
          grantee,
        },
      },
      fee,
      memo,
      _funds
    );
  };
}
