/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, InstantiateMsg, ExecuteMsg, Uint256, RegistrationModeConfig, VoiceCreditMode, Timestamp, Uint64, Decimal, Uint128, PubKey, WhitelistBase, WhitelistBaseConfig, RoundInfo, VotingTime, ValidatorSet, CircuitChargeConfig, FeeConfig, DelayConfig, QueryMsg, AdminResponse, String, NullableAddr, Boolean } from "./Registry.types";
export interface RegistryReadOnlyInterface {
  contractAddress: string;
  admin: () => Promise<AdminResponse>;
  operator: () => Promise<Addr>;
  isMaciOperator: ({
    address
  }: {
    address: Addr;
  }) => Promise<Boolean>;
  isValidator: ({
    address
  }: {
    address: Addr;
  }) => Promise<Boolean>;
  getValidators: () => Promise<ValidatorSet>;
  getValidatorOperator: ({
    address
  }: {
    address: Addr;
  }) => Promise<Addr>;
  getMaciOperatorPubkey: ({
    address
  }: {
    address: Addr;
  }) => Promise<PubKey>;
  getMaciOperatorIdentity: ({
    address
  }: {
    address: Addr;
  }) => Promise<String>;
  getCircuitChargeConfig: () => Promise<CircuitChargeConfig>;
  getFeeConfig: () => Promise<FeeConfig>;
  getDelayConfig: () => Promise<DelayConfig>;
  getPollId: ({
    address
  }: {
    address: Addr;
  }) => Promise<Uint64>;
  getPollAddress: ({
    pollId
  }: {
    pollId: number;
  }) => Promise<NullableAddr>;
  getNextPollId: () => Promise<Uint64>;
  getAmaciCodeId: () => Promise<Uint64>;
}
export class RegistryQueryClient implements RegistryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.admin = this.admin.bind(this);
    this.operator = this.operator.bind(this);
    this.isMaciOperator = this.isMaciOperator.bind(this);
    this.isValidator = this.isValidator.bind(this);
    this.getValidators = this.getValidators.bind(this);
    this.getValidatorOperator = this.getValidatorOperator.bind(this);
    this.getMaciOperatorPubkey = this.getMaciOperatorPubkey.bind(this);
    this.getMaciOperatorIdentity = this.getMaciOperatorIdentity.bind(this);
    this.getCircuitChargeConfig = this.getCircuitChargeConfig.bind(this);
    this.getFeeConfig = this.getFeeConfig.bind(this);
    this.getDelayConfig = this.getDelayConfig.bind(this);
    this.getPollId = this.getPollId.bind(this);
    this.getPollAddress = this.getPollAddress.bind(this);
    this.getNextPollId = this.getNextPollId.bind(this);
    this.getAmaciCodeId = this.getAmaciCodeId.bind(this);
  }
  admin = async (): Promise<AdminResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin: {}
    });
  };
  operator = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operator: {}
    });
  };
  isMaciOperator = async ({
    address
  }: {
    address: Addr;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_maci_operator: {
        address
      }
    });
  };
  isValidator = async ({
    address
  }: {
    address: Addr;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_validator: {
        address
      }
    });
  };
  getValidators = async (): Promise<ValidatorSet> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_validators: {}
    });
  };
  getValidatorOperator = async ({
    address
  }: {
    address: Addr;
  }): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_validator_operator: {
        address
      }
    });
  };
  getMaciOperatorPubkey = async ({
    address
  }: {
    address: Addr;
  }): Promise<PubKey> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_maci_operator_pubkey: {
        address
      }
    });
  };
  getMaciOperatorIdentity = async ({
    address
  }: {
    address: Addr;
  }): Promise<String> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_maci_operator_identity: {
        address
      }
    });
  };
  getCircuitChargeConfig = async (): Promise<CircuitChargeConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_circuit_charge_config: {}
    });
  };
  getFeeConfig = async (): Promise<FeeConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_fee_config: {}
    });
  };
  getDelayConfig = async (): Promise<DelayConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_delay_config: {}
    });
  };
  getPollId = async ({
    address
  }: {
    address: Addr;
  }): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_poll_id: {
        address
      }
    });
  };
  getPollAddress = async ({
    pollId
  }: {
    pollId: number;
  }): Promise<NullableAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_poll_address: {
        poll_id: pollId
      }
    });
  };
  getNextPollId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_next_poll_id: {}
    });
  };
  getAmaciCodeId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_amaci_code_id: {}
    });
  };
}
export interface RegistryInterface extends RegistryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  setMaciOperator: ({
    operator
  }: {
    operator: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setMaciOperatorPubkey: ({
    pubkey
  }: {
    pubkey: PubKey;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setMaciOperatorIdentity: ({
    identity
  }: {
    identity: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createRound: ({
    certificationSystem,
    circuitType,
    deactivateEnabled,
    operator,
    registrationMode,
    roundInfo,
    voiceCreditMode,
    voteOptionMap,
    votingTime
  }: {
    certificationSystem: Uint256;
    circuitType: Uint256;
    deactivateEnabled: boolean;
    operator: Addr;
    registrationMode: RegistrationModeConfig;
    roundInfo: RoundInfo;
    voiceCreditMode: VoiceCreditMode;
    voteOptionMap: string[];
    votingTime: VotingTime;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setValidators: ({
    addresses
  }: {
    addresses: ValidatorSet;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeValidator: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAmaciCodeId: ({
    codeId
  }: {
    codeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  changeOperator: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  changeChargeConfig: ({
    config
  }: {
    config: CircuitChargeConfig;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateFeeConfig: ({
    config
  }: {
    config: FeeConfig;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateDelayConfig: ({
    config
  }: {
    config: DelayConfig;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class RegistryClient extends RegistryQueryClient implements RegistryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setMaciOperator = this.setMaciOperator.bind(this);
    this.setMaciOperatorPubkey = this.setMaciOperatorPubkey.bind(this);
    this.setMaciOperatorIdentity = this.setMaciOperatorIdentity.bind(this);
    this.createRound = this.createRound.bind(this);
    this.setValidators = this.setValidators.bind(this);
    this.removeValidator = this.removeValidator.bind(this);
    this.updateAmaciCodeId = this.updateAmaciCodeId.bind(this);
    this.changeOperator = this.changeOperator.bind(this);
    this.changeChargeConfig = this.changeChargeConfig.bind(this);
    this.updateFeeConfig = this.updateFeeConfig.bind(this);
    this.updateDelayConfig = this.updateDelayConfig.bind(this);
  }
  setMaciOperator = async ({
    operator
  }: {
    operator: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_maci_operator: {
        operator
      }
    }, fee, memo, _funds);
  };
  setMaciOperatorPubkey = async ({
    pubkey
  }: {
    pubkey: PubKey;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_maci_operator_pubkey: {
        pubkey
      }
    }, fee, memo, _funds);
  };
  setMaciOperatorIdentity = async ({
    identity
  }: {
    identity: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_maci_operator_identity: {
        identity
      }
    }, fee, memo, _funds);
  };
  createRound = async ({
    certificationSystem,
    circuitType,
    deactivateEnabled,
    operator,
    registrationMode,
    roundInfo,
    voiceCreditMode,
    voteOptionMap,
    votingTime
  }: {
    certificationSystem: Uint256;
    circuitType: Uint256;
    deactivateEnabled: boolean;
    operator: Addr;
    registrationMode: RegistrationModeConfig;
    roundInfo: RoundInfo;
    voiceCreditMode: VoiceCreditMode;
    voteOptionMap: string[];
    votingTime: VotingTime;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_round: {
        certification_system: certificationSystem,
        circuit_type: circuitType,
        deactivate_enabled: deactivateEnabled,
        operator,
        registration_mode: registrationMode,
        round_info: roundInfo,
        voice_credit_mode: voiceCreditMode,
        vote_option_map: voteOptionMap,
        voting_time: votingTime
      }
    }, fee, memo, _funds);
  };
  setValidators = async ({
    addresses
  }: {
    addresses: ValidatorSet;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_validators: {
        addresses
      }
    }, fee, memo, _funds);
  };
  removeValidator = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_validator: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAmaciCodeId = async ({
    codeId
  }: {
    codeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_amaci_code_id: {
        code_id: codeId
      }
    }, fee, memo, _funds);
  };
  changeOperator = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_operator: {
        address
      }
    }, fee, memo, _funds);
  };
  changeChargeConfig = async ({
    config
  }: {
    config: CircuitChargeConfig;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_charge_config: {
        config
      }
    }, fee, memo, _funds);
  };
  updateFeeConfig = async ({
    config
  }: {
    config: FeeConfig;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_fee_config: {
        config
      }
    }, fee, memo, _funds);
  };
  updateDelayConfig = async ({
    config
  }: {
    config: DelayConfig;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_delay_config: {
        config
      }
    }, fee, memo, _funds);
  };
}