/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  admin: Addr;
  amaci_code_id: number;
  operator: Addr;
}
export type ExecuteMsg = {
  set_maci_operator: {
    operator: Addr;
  };
} | {
  set_maci_operator_pubkey: {
    pubkey: PubKey;
  };
} | {
  set_maci_operator_identity: {
    identity: string;
  };
} | {
  create_round: {
    certification_system: Uint256;
    circuit_type: Uint256;
    deactivate_enabled: boolean;
    operator: Addr;
    registration_mode: RegistrationModeConfig;
    round_info: RoundInfo;
    voice_credit_mode: VoiceCreditMode;
    vote_option_map: string[];
    voting_time: VotingTime;
  };
} | {
  set_validators: {
    addresses: ValidatorSet;
  };
} | {
  remove_validator: {
    address: Addr;
  };
} | {
  update_amaci_code_id: {
    code_id: number;
  };
} | {
  change_operator: {
    address: Addr;
  };
} | {
  change_charge_config: {
    config: CircuitChargeConfig;
  };
} | {
  update_fee_config: {
    config: FeeConfig;
  };
} | {
  update_delay_config: {
    config: DelayConfig;
  };
};
export type Uint256 = string;
export type RegistrationModeConfig = {
  sign_up_with_static_whitelist: {
    whitelist: WhitelistBase;
  };
} | {
  sign_up_with_oracle: {
    oracle_pubkey: string;
  };
} | {
  pre_populated: {
    pre_deactivate_coordinator: PubKey;
    pre_deactivate_root: Uint256;
  };
};
export type VoiceCreditMode = "dynamic" | {
  unified: {
    amount: Uint256;
  };
};
export type Timestamp = Uint64;
export type Uint64 = number;
export type Decimal = string;
export type Uint128 = string;
export interface PubKey {
  x: Uint256;
  y: Uint256;
}
export interface WhitelistBase {
  users: WhitelistBaseConfig[];
}
export interface WhitelistBaseConfig {
  addr: Addr;
  voice_credit_amount?: Uint256 | null;
}
export interface RoundInfo {
  description: string;
  link: string;
  title: string;
}
export interface VotingTime {
  end_time: Timestamp;
  start_time: Timestamp;
}
export interface ValidatorSet {
  addresses: Addr[];
}
export interface CircuitChargeConfig {
  fee_rate: Decimal;
}
export interface FeeConfig {
  base_fee: Uint128;
  deactivate_fee: Uint128;
  message_fee: Uint128;
  signup_fee: Uint128;
}
export interface DelayConfig {
  base_delay: number;
  deactivate_delay: number;
  message_delay: number;
  signup_delay: number;
}
export type QueryMsg = {
  admin: {};
} | {
  operator: {};
} | {
  is_maci_operator: {
    address: Addr;
  };
} | {
  is_validator: {
    address: Addr;
  };
} | {
  get_validators: {};
} | {
  get_validator_operator: {
    address: Addr;
  };
} | {
  get_maci_operator_pubkey: {
    address: Addr;
  };
} | {
  get_maci_operator_identity: {
    address: Addr;
  };
} | {
  get_circuit_charge_config: {};
} | {
  get_fee_config: {};
} | {
  get_delay_config: {};
} | {
  get_poll_id: {
    address: Addr;
  };
} | {
  get_poll_address: {
    poll_id: number;
  };
} | {
  get_next_poll_id: {};
} | {
  get_amaci_code_id: {};
};
export interface AdminResponse {
  admin: Addr;
}
export type String = string;
export type NullableAddr = Addr | null;
export type Boolean = boolean;