/**
 * Load and parse crypto test vectors from Rust
 */

import * as fs from 'fs';
import * as path from 'path';
import type { CryptoTestVector } from './test-vectors';

const VECTORS_FILE = path.join(__dirname, 'test-vectors-rust.json');

/**
 * Check if test vectors file exists
 */
export function vectorsExist(): boolean {
  return fs.existsSync(VECTORS_FILE);
}

/**
 * Load all test vectors from JSON file
 */
export function loadCryptoTestVectors(): CryptoTestVector[] {
  if (!vectorsExist()) {
    throw new Error(
      'Crypto test vectors not found. They should be auto-generated by pretest:crypto hook.\n' +
        'If this error occurs, try running: cd crates/maci-crypto && cargo run --bin generate_crypto_test_vectors'
    );
  }

  const jsonContent = fs.readFileSync(VECTORS_FILE, 'utf-8');
  const vectors: CryptoTestVector[] = JSON.parse(jsonContent);

  return vectors;
}

/**
 * Find a test vector by name
 */
export function findVector(
  vectors: CryptoTestVector[],
  name: string
): CryptoTestVector | undefined {
  return vectors.find((v) => v.name === name);
}

/**
 * Filter vectors by test type
 */
export function filterByType(
  vectors: CryptoTestVector[],
  testType: CryptoTestVector['test_type']
): CryptoTestVector[] {
  return vectors.filter((v) => v.test_type === testType);
}

