/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, InstantiateMsg, ExecuteMsg, Uint128, Uint256, RegistrationModeConfig, VoiceCreditMode, Timestamp, Uint64, WhitelistBase, WhitelistBaseConfig, PubKey, RoundInfo, VotingTime, SaasFeeConfig, EncPubKeyParam, MessageDataParam, Groth16ProofParam, QueryMsg, Config, Boolean, ArrayOfOperatorInfo, OperatorInfo } from "./ApiSaas.types";
export interface ApiSaasReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  operators: () => Promise<ArrayOfOperatorInfo>;
  isOperator: ({
    address
  }: {
    address: Addr;
  }) => Promise<Boolean>;
  balance: () => Promise<Uint128>;
  treasuryManager: () => Promise<Addr>;
}
export class ApiSaasQueryClient implements ApiSaasReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.operators = this.operators.bind(this);
    this.isOperator = this.isOperator.bind(this);
    this.balance = this.balance.bind(this);
    this.treasuryManager = this.treasuryManager.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  operators = async (): Promise<ArrayOfOperatorInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operators: {}
    });
  };
  isOperator = async ({
    address
  }: {
    address: Addr;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_operator: {
        address
      }
    });
  };
  balance = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {}
    });
  };
  treasuryManager = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      treasury_manager: {}
    });
  };
}
export interface ApiSaasInterface extends ApiSaasReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    admin,
    denom
  }: {
    admin?: Addr;
    denom?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAmaciRegistryContract: ({
    registryContract
  }: {
    registryContract: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addOperator: ({
    operator
  }: {
    operator: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeOperator: ({
    operator
  }: {
    operator: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deposit: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient?: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createAmaciRound: ({
    certificationSystem,
    circuitType,
    deactivateEnabled,
    operator,
    registrationMode,
    roundInfo,
    voiceCreditMode,
    voteOptionMap,
    votingTime
  }: {
    certificationSystem: Uint256;
    circuitType: Uint256;
    deactivateEnabled: boolean;
    operator: Addr;
    registrationMode: RegistrationModeConfig;
    roundInfo: RoundInfo;
    voiceCreditMode: VoiceCreditMode;
    voteOptionMap: string[];
    votingTime: VotingTime;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateFeeConfig: ({
    config
  }: {
    config: SaasFeeConfig;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setRoundInfo: ({
    contractAddr,
    roundInfo
  }: {
    contractAddr: string;
    roundInfo: RoundInfo;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setVoteOptionsMap: ({
    contractAddr,
    voteOptionMap
  }: {
    contractAddr: string;
    voteOptionMap: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  publishMessage: ({
    contractAddr,
    encPubKeys,
    messages
  }: {
    contractAddr: string;
    encPubKeys: EncPubKeyParam[];
    messages: MessageDataParam[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  publishDeactivateMessage: ({
    contractAddr,
    encPubKey,
    message
  }: {
    contractAddr: string;
    encPubKey: EncPubKeyParam;
    message: MessageDataParam;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  signUp: ({
    amount,
    certificate,
    contractAddr,
    pubkey
  }: {
    amount?: string;
    certificate?: string;
    contractAddr: string;
    pubkey: EncPubKeyParam;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addNewKey: ({
    contractAddr,
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    contractAddr: string;
    d: string[];
    groth16Proof: Groth16ProofParam;
    nullifier: string;
    pubkey: EncPubKeyParam;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  preAddNewKey: ({
    contractAddr,
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    contractAddr: string;
    d: string[];
    groth16Proof: Groth16ProofParam;
    nullifier: string;
    pubkey: EncPubKeyParam;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ApiSaasClient extends ApiSaasQueryClient implements ApiSaasInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.updateAmaciRegistryContract = this.updateAmaciRegistryContract.bind(this);
    this.addOperator = this.addOperator.bind(this);
    this.removeOperator = this.removeOperator.bind(this);
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.createAmaciRound = this.createAmaciRound.bind(this);
    this.updateFeeConfig = this.updateFeeConfig.bind(this);
    this.setRoundInfo = this.setRoundInfo.bind(this);
    this.setVoteOptionsMap = this.setVoteOptionsMap.bind(this);
    this.publishMessage = this.publishMessage.bind(this);
    this.publishDeactivateMessage = this.publishDeactivateMessage.bind(this);
    this.signUp = this.signUp.bind(this);
    this.addNewKey = this.addNewKey.bind(this);
    this.preAddNewKey = this.preAddNewKey.bind(this);
  }
  updateConfig = async ({
    admin,
    denom
  }: {
    admin?: Addr;
    denom?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        admin,
        denom
      }
    }, fee, memo, _funds);
  };
  updateAmaciRegistryContract = async ({
    registryContract
  }: {
    registryContract: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_amaci_registry_contract: {
        registry_contract: registryContract
      }
    }, fee, memo, _funds);
  };
  addOperator = async ({
    operator
  }: {
    operator: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_operator: {
        operator
      }
    }, fee, memo, _funds);
  };
  removeOperator = async ({
    operator
  }: {
    operator: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_operator: {
        operator
      }
    }, fee, memo, _funds);
  };
  deposit = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit: {}
    }, fee, memo, _funds);
  };
  withdraw = async ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient?: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        amount,
        recipient
      }
    }, fee, memo, _funds);
  };
  createAmaciRound = async ({
    certificationSystem,
    circuitType,
    deactivateEnabled,
    operator,
    registrationMode,
    roundInfo,
    voiceCreditMode,
    voteOptionMap,
    votingTime
  }: {
    certificationSystem: Uint256;
    circuitType: Uint256;
    deactivateEnabled: boolean;
    operator: Addr;
    registrationMode: RegistrationModeConfig;
    roundInfo: RoundInfo;
    voiceCreditMode: VoiceCreditMode;
    voteOptionMap: string[];
    votingTime: VotingTime;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_amaci_round: {
        certification_system: certificationSystem,
        circuit_type: circuitType,
        deactivate_enabled: deactivateEnabled,
        operator,
        registration_mode: registrationMode,
        round_info: roundInfo,
        voice_credit_mode: voiceCreditMode,
        vote_option_map: voteOptionMap,
        voting_time: votingTime
      }
    }, fee, memo, _funds);
  };
  updateFeeConfig = async ({
    config
  }: {
    config: SaasFeeConfig;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_fee_config: {
        config
      }
    }, fee, memo, _funds);
  };
  setRoundInfo = async ({
    contractAddr,
    roundInfo
  }: {
    contractAddr: string;
    roundInfo: RoundInfo;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_round_info: {
        contract_addr: contractAddr,
        round_info: roundInfo
      }
    }, fee, memo, _funds);
  };
  setVoteOptionsMap = async ({
    contractAddr,
    voteOptionMap
  }: {
    contractAddr: string;
    voteOptionMap: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_vote_options_map: {
        contract_addr: contractAddr,
        vote_option_map: voteOptionMap
      }
    }, fee, memo, _funds);
  };
  publishMessage = async ({
    contractAddr,
    encPubKeys,
    messages
  }: {
    contractAddr: string;
    encPubKeys: EncPubKeyParam[];
    messages: MessageDataParam[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      publish_message: {
        contract_addr: contractAddr,
        enc_pub_keys: encPubKeys,
        messages
      }
    }, fee, memo, _funds);
  };
  publishDeactivateMessage = async ({
    contractAddr,
    encPubKey,
    message
  }: {
    contractAddr: string;
    encPubKey: EncPubKeyParam;
    message: MessageDataParam;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      publish_deactivate_message: {
        contract_addr: contractAddr,
        enc_pub_key: encPubKey,
        message
      }
    }, fee, memo, _funds);
  };
  signUp = async ({
    amount,
    certificate,
    contractAddr,
    pubkey
  }: {
    amount?: string;
    certificate?: string;
    contractAddr: string;
    pubkey: EncPubKeyParam;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      sign_up: {
        amount,
        certificate,
        contract_addr: contractAddr,
        pubkey
      }
    }, fee, memo, _funds);
  };
  addNewKey = async ({
    contractAddr,
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    contractAddr: string;
    d: string[];
    groth16Proof: Groth16ProofParam;
    nullifier: string;
    pubkey: EncPubKeyParam;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_new_key: {
        contract_addr: contractAddr,
        d,
        groth16_proof: groth16Proof,
        nullifier,
        pubkey
      }
    }, fee, memo, _funds);
  };
  preAddNewKey = async ({
    contractAddr,
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    contractAddr: string;
    d: string[];
    groth16Proof: Groth16ProofParam;
    nullifier: string;
    pubkey: EncPubKeyParam;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pre_add_new_key: {
        contract_addr: contractAddr,
        d,
        groth16_proof: groth16Proof,
        nullifier,
        pubkey
      }
    }, fee, memo, _funds);
  };
}