/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  admin: Addr;
  denom: string;
  registry_contract: Addr;
  treasury_manager: Addr;
}
export type ExecuteMsg = {
  update_config: {
    admin?: Addr | null;
    denom?: string | null;
  };
} | {
  update_amaci_registry_contract: {
    registry_contract: Addr;
  };
} | {
  add_operator: {
    operator: Addr;
  };
} | {
  remove_operator: {
    operator: Addr;
  };
} | {
  deposit: {};
} | {
  withdraw: {
    amount: Uint128;
    recipient?: Addr | null;
  };
} | {
  create_amaci_round: {
    certification_system: Uint256;
    circuit_type: Uint256;
    deactivate_enabled: boolean;
    max_voter: Uint256;
    operator: Addr;
    registration_mode: RegistrationModeConfig;
    round_info: RoundInfo;
    voice_credit_mode: VoiceCreditMode;
    vote_option_map: string[];
    voting_time: VotingTime;
  };
} | {
  set_round_info: {
    contract_addr: string;
    round_info: RoundInfo;
  };
} | {
  set_vote_options_map: {
    contract_addr: string;
    vote_option_map: string[];
  };
} | {
  publish_message: {
    contract_addr: string;
    enc_pub_keys: EncPubKeyParam[];
    messages: MessageDataParam[];
  };
} | {
  publish_deactivate_message: {
    contract_addr: string;
    enc_pub_key: EncPubKeyParam;
    message: MessageDataParam;
  };
};
export type Uint128 = string;
export type Uint256 = string;
export type RegistrationModeConfig = {
  sign_up_with_static_whitelist: {
    whitelist: WhitelistBase;
  };
} | {
  sign_up_with_oracle: {
    oracle_pubkey: string;
  };
} | {
  pre_populated: {
    pre_deactivate_coordinator: PubKey;
    pre_deactivate_root: Uint256;
  };
};
export type VoiceCreditMode = "dynamic" | {
  unified: {
    amount: Uint256;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface WhitelistBase {
  users: WhitelistBaseConfig[];
}
export interface WhitelistBaseConfig {
  addr: Addr;
  voice_credit_amount?: Uint256 | null;
}
export interface PubKey {
  x: Uint256;
  y: Uint256;
}
export interface RoundInfo {
  description: string;
  link: string;
  title: string;
}
export interface VotingTime {
  end_time: Timestamp;
  start_time: Timestamp;
}
export interface EncPubKeyParam {
  x: string;
  y: string;
}
export interface MessageDataParam {
  data: string[];
}
export type QueryMsg = {
  config: {};
} | {
  operators: {};
} | {
  is_operator: {
    address: Addr;
  };
} | {
  balance: {};
} | {
  treasury_manager: {};
};
export interface Config {
  admin: Addr;
  denom: string;
}
export type Boolean = boolean;
export type ArrayOfOperatorInfo = OperatorInfo[];
export interface OperatorInfo {
  added_at: Timestamp;
  address: Addr;
}