/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns basic liveness of the API service (database connection check).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Service liveness flag */
              ok: boolean;
              /**
               * Format: date-time
               * @description Server ISO timestamp
               */
              time: string;
              /** @description Optional app version/commit */
              version?: string | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/pools': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Account pool status
     * @description Returns account pool status for both orchestrator (Redis) and pre-generated (Database) pools.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * Format: date-time
               * @description Server ISO timestamp
               */
              timestamp: string;
              /** @description Orchestrator operator account pool status (Redis) */
              orchestratorPool: {
                /** @description Total accounts in pool (configured max) */
                total: number;
                /** @description Number of available accounts */
                available: number;
                /** @description Number of locked accounts */
                locked: number;
                /** @description Percentage of accounts locked */
                usagePercentage: number;
              };
              /** @description Pre-generated account pool status (Database) */
              preGeneratedPool: {
                /** @description Number of available pre-generated accounts */
                available: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create API key
     * @description Creates an API key bound to an existing tenant. Requires X-Admin-Secret header.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Tenant ULID */
            tenantId: string;
            /** @description Optional key label */
            label?: string;
            /**
             * @description Plan id: free|pro|enterprise
             * @default free
             * @enum {string}
             */
            plan?: 'free' | 'pro' | 'enterprise';
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Secret, shown only once */
              apiKey: string;
              /** @description Public key prefix */
              prefix: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usage for current API key
     * @description Returns paginated usage events attributed to the calling API key.
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (1-based) */
          page?: number;
          /** @description Items per page */
          pageSize?: number;
          /** @description Filter: created_at >= from */
          from?: string;
          /** @description Filter: created_at < to */
          to?: string;
          /** @description Filter by endpoint (e.g., signup|vote|create_round) */
          endpoint?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items: {
                /** @description Usage event ULID */
                id: string;
                endpoint: string;
                statusCode: number;
                costUnits: number;
                meta?: {
                  [key: string]: string | number | boolean | null;
                } | null;
                /** Format: date-time */
                createdAt: string;
              }[];
              page: number;
              pageSize: number;
              totalItems: number;
              totalPages: number;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              details?: {
                [key: string]: string | number | boolean | null;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              details?: {
                [key: string]: string | number | boolean | null;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signup */
    post: operations['signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/vote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Vote */
    post: operations['vote'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/create-round': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Round */
    post: operations['createRound'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/create-amaci-round': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create AMaci Round */
    post: operations['createAmaciRound'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/set-round-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set Round Info */
    post: operations['setRoundInfo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/set-vote-options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set Vote Options */
    post: operations['setVoteOptions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate */
    post: operations['deactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/add-new-key': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add New Key */
    post: operations['addNewKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/pre-add-new-key': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pre Add New Key */
    post: operations['preAddNewKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tenants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create tenant
     * @description Creates a new tenant that will own API keys. Requires X-Admin-Secret header.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Tenant display name */
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description ULID */
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              details?: {
                [key: string]: string | number | boolean | null;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/allowlists/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Allowlist List */
    get: operations['getAllowlists'];
    put?: never;
    /** Create Allowlist */
    post: operations['createAllowlist'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/allowlists/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Allowlist Details */
    get: operations['getAllowlistDetail'];
    /** Update Allowlist */
    put: operations['updateAllowlist'];
    post?: never;
    /** Delete Allowlist */
    delete: operations['deleteAllowlist'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/allowlists/snapshots/{contractAddress}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Round Allowlist Snapshot */
    get: operations['getRoundAllowlistSnapshot'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/certificates/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description User's MACI public key (hexadecimal string) */
            pubkey: string;
            /** @description Contract address */
            contractAddress: string;
            /** @description User's signature on {pubkey, contract_address} using eddsa_poseidon */
            signature: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description User public key */
              pubkey: string;
              /** @description Contract address */
              contractAddress: string;
              /** @description Certificate signature issued by backend */
              certificate: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/pre-deactivate/pool/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get pre-computed deactivate tree pool status per voter scale */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Coordinator public key prefix */
              coordinator: string;
              /** @description Tree pool status per voter scale */
              scales: {
                /** @description Voter scale (10 | 20 | 50 | 100) */
                scale: number;
                /** @description Number of ready trees */
                ready: number;
                /** @description Number of trees being generated */
                pending: number;
                /** @description Total trees for this scale */
                total: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/pre-deactivate/{contractAddress}/proof': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return Merkle proof packages for the requested leaf indices (K-anonymous). The client sends K indices (true index mixed with K-1 decoys); the server cannot distinguish the true leaf, providing K-anonymity. */
    get: {
      parameters: {
        query: {
          /** @description Comma-separated leaf indices to retrieve proofs for (K-anonymous request) */
          indices: string;
        };
        header?: never;
        path: {
          contractAddress: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Extended deactivate Merkle root */
              root: string;
              /** @description One proof package per requested leaf index */
              proofs: {
                /** @description Leaf index in the tree */
                leafIndex: number;
                /** @description Raw deactivate leaf: [c1.x, c1.y, c2.x, c2.y, sharedKeyHash] */
                deactivateLeaf: string[];
                /** @description Poseidon hash of deactivateLeaf */
                deactivateLeafHash: string;
                /** @description Sibling hashes per level (stateTreeDepth+2 levels × 4 siblings) */
                pathElements: string[][];
                /** @description Child position at each level (stateTreeDepth+2 values, each in [0,5)) */
                pathIndices: number[];
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/pre-deactivate/{contractAddress}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get pre-deactivate data by contract address */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          contractAddress: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Snapshot or tree ID */
              id: string;
              /** @description Contract address */
              contractAddress: string;
              /** @description Deactivate root */
              root: string;
              /** @description Coordinator public key */
              coordinator: string;
              /** @description Merkle tree depth used for proof generation (e.g. 2, 4, or 6) */
              stateTreeDepth: number;
              /** @description Array of leaf hashes (deactivateLeafHash) */
              leaves: string[];
              /** @description Array of deactivate leaf data arrays */
              deactivates: string[][];
              /** @description Creation timestamp */
              createdAt: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description AMACI public key of the voter */
          pubkey: string;
          /** @description Round ID (contract address) */
          contractAddress: string;
          /** @description Oracle certificate information */
          certificate: string;
          /** @description Voice credit amount (optional, defaults to "1") */
          amount?: string;
          /** @description Round ticket (JWT) for authentication */
          ticket: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  vote: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Round ID (contract address) */
          contractAddress: string;
          /** @description Array of vote messages */
          payload: {
            /** @description Serialized MACI vote message (10 elements) */
            msg: string[];
            /** @description Encrypted public keys (2 elements) */
            encPubkeys: string[];
          }[];
          /** @description Round ticket (JWT) for authentication */
          ticket: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  createRound: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Human-readable round title */
          title: string;
          /** @description Round description */
          description?: string;
          /** @description Related link */
          link?: string;
          /** @description Voting start time (ISO 8601) */
          startVoting: string;
          /** @description Voting end time (ISO 8601) */
          endVoting: string;
          /** @description Operator public key */
          operatorPubkey: string;
          /** @description Maximum number of voters (max: 15625) */
          maxVoter: number;
          /** @description Array of voting options (max: 125 options) */
          voteOptionMap: string[];
          /** @description MACI circuit type */
          circuitType?: string;
          /** @description Whitelist backend public key */
          whitelistBackendPubkey?: string;
          /** @description Fee grant operator */
          feegrantOperator?: string;
          /** @description Allowlist ID for whitelist */
          allowlistId: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  createAmaciRound: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Human-readable round title */
          title: string;
          /** @description Round description */
          description?: string;
          /** @description Related link */
          link?: string;
          /** @description Voting start time (ISO 8601) */
          startVoting: string;
          /** @description Voting end time (ISO 8601) */
          endVoting: string;
          /** @description Operator address */
          operator: string;
          /** @description Maximum number of voters (max: 15625) */
          maxVoter: number;
          /** @description Array of voting options (max: 125 options) */
          voteOptionMap: string[];
          /** @description MACI circuit type */
          circuitType?: string;
          /** @description Voice credit amount */
          voiceCreditAmount: number;
          /** @description Allowlist ID for whitelist. If not provided, pre-deactivate mode will be used automatically */
          allowlistId?: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  setRoundInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description MACI contract address */
          contractAddress: string;
          /** @description Round title */
          title: string;
          /** @description Round description */
          description: string;
          /** @description Related link */
          link: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  setVoteOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description MACI contract address */
          contractAddress: string;
          /** @description Array of voting options */
          voteOptionMap: string[];
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description MACI contract address */
          contractAddress: string;
          /** @description Deactivate payload */
          payload: {
            /** @description Deactivate message array */
            msg: string[];
            /** @description Encrypted public keys (2 elements) */
            encPubkeys: string[];
          };
          /** @description Round ticket (JWT) for authentication */
          ticket: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  addNewKey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description MACI contract address */
          contractAddress: string;
          /** @description Groth16 proof */
          proof: {
            /** @description Groth16 proof component a */
            a: string;
            /** @description Groth16 proof component b */
            b: string;
            /** @description Groth16 proof component c */
            c: string;
          };
          /** @description Array d from addKeyInput (4 elements) */
          d: string[];
          /** @description Nullifier from addKeyInput */
          nullifier: string;
          /** @description New public key (2 elements) */
          newPubkey: string[];
          /** @description Round ticket (JWT) for authentication */
          ticket: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  preAddNewKey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description MACI contract address */
          contractAddress: string;
          /** @description Groth16 proof */
          proof: {
            /** @description Groth16 proof component a */
            a: string;
            /** @description Groth16 proof component b */
            b: string;
            /** @description Groth16 proof component c */
            c: string;
          };
          /** @description Array d from preAddKeyInput (4 elements) */
          d: string[];
          /** @description Nullifier from preAddKeyInput */
          nullifier: string;
          /** @description New public key (2 elements) */
          newPubkey: string[];
          /** @description Round ticket (JWT) for authentication */
          ticket: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Internal request id (ULID/UUID) */
            id: string;
            /** @description Transaction hash */
            txHash: string;
            /** @description Block height (0 if not available) */
            height: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: 'confirmed' | 'failed';
            /** @description Contract address (for successful transactions) */
            contractAddress?: string;
            /** @description Round ticket (JWT) for accessing round operations */
            ticket?: string;
            /** @description Error message (for failed transactions) */
            error?: string;
            /** @description Pre-generated accounts (for pre-deactivate mode only) */
            accounts?: {
              /** @description Account public key */
              pubkey: string;
              /** @description Account secret key */
              secretKey: string;
              /** @description Leaf index of this account in the deactivate tree */
              accountIndex: number;
            }[];
            /** @description Pre-deactivate Merkle tree root (for pre-deactivate mode only) */
            preDeactivateRoot?: string;
            /** @description Pre-deactivate tree capacity / voter scale (for pre-deactivate mode only) */
            preDeactivateScale?: number;
          };
        };
      };
    };
  };
  getAllowlists: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Filter only active allowlists */
        activeOnly?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            allowlists: {
              /** @description ULID */
              id: string;
              /** @description Allowlist name */
              name: string;
              /** @description Allowlist description */
              description: string | null;
              /** @description Whether allowlist is active */
              isActive: boolean;
              /** @description Number of items in allowlist */
              itemCount: number;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            total: number;
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  createAllowlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Allowlist name */
          name: string;
          /** @description Allowlist description */
          description?: string;
          /** @description Array of public keys to add to allowlist */
          pubkeys: string[];
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description ULID */
            id: string;
            /** @description Allowlist name */
            name: string;
            /** @description Allowlist description */
            description: string | null;
            /** @description Whether allowlist is active */
            isActive: boolean;
            /** @description Number of items in allowlist */
            itemCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getAllowlistDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Allowlist ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description ULID */
            id: string;
            /** @description Allowlist name */
            name: string;
            /** @description Allowlist description */
            description: string | null;
            /** @description Whether allowlist is active */
            isActive: boolean;
            /** @description Allowlist items */
            items: {
              /** @description ULID */
              id: string;
              /** @description Public key */
              pubkey: string;
              /** Format: date-time */
              createdAt: string;
            }[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      /** @description Default Response */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  updateAllowlist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Allowlist ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /** @description Allowlist name */
          name?: string;
          /** @description Allowlist description */
          description?: string;
          /** @description Public keys to add */
          pubkeysToAdd?: string[];
          /** @description Public keys to remove */
          pubkeysToRemove?: string[];
          /** @description Whether allowlist is active */
          isActive?: boolean;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description ULID */
            id: string;
            /** @description Allowlist name */
            name: string;
            /** @description Allowlist description */
            description: string | null;
            /** @description Whether allowlist is active */
            isActive: boolean;
            /** @description Number of items in allowlist */
            itemCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  deleteAllowlist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Allowlist ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': null;
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getRoundAllowlistSnapshot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Round contract address */
        contractAddress: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description ULID */
            id: string;
            /** @description Allowlist ID */
            allowlistId: string;
            /** @description Round ID (contract address) */
            roundId: string;
            /** @description Number of pubkeys in snapshot */
            pubkeyCount: number;
            /** @description Snapshot data */
            snapshotData: {
              name: string;
              description: string | null;
              pubkeys: string[];
            };
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
      /** @description Default Response */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
}
