/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, Uint256, Uint128, RegistrationModeConfig, VoiceCreditMode, Timestamp, Uint64, InstantiateMsg, PubKey, MaciParameters, WhitelistBase, WhitelistBaseConfig, RoundInfo, VotingTime, ExecuteMsg, RegistrationConfigUpdate, MessageData, Groth16ProofType, QueryMsg, ArrayOfUint256, Boolean, DelayConfigResponse, DelayType, DelayRecords, DelayRecord, FeeConfigResponse, PeriodStatus, Period, RegistrationMode, RegistrationConfigInfo, TallyDelayInfo, NullableString, NullableUint256, RegistrationStatus, ArrayOfString } from "./AMaci.types";
export interface AMaciReadOnlyInterface {
  contractAddress: string;
  admin: () => Promise<Addr>;
  operator: () => Promise<Addr>;
  getRoundInfo: () => Promise<RoundInfo>;
  getVotingTime: () => Promise<VotingTime>;
  getPeriod: () => Promise<Period>;
  getNumSignUp: () => Promise<Uint256>;
  getMsgChainLength: () => Promise<Uint256>;
  getDMsgChainLength: () => Promise<Uint256>;
  getProcessedDMsgCount: () => Promise<Uint256>;
  getProcessedMsgCount: () => Promise<Uint256>;
  getProcessedUserCount: () => Promise<Uint256>;
  getStateTreeRoot: () => Promise<Uint256>;
  getNode: ({
    index
  }: {
    index: Uint256;
  }) => Promise<Uint256>;
  getResult: ({
    index
  }: {
    index: Uint256;
  }) => Promise<Uint256>;
  getAllResult: () => Promise<Uint256>;
  getAllResults: () => Promise<ArrayOfUint256>;
  getStateIdxInc: ({
    address
  }: {
    address: Addr;
  }) => Promise<Uint256>;
  getVoiceCreditBalance: ({
    index
  }: {
    index: Uint256;
  }) => Promise<Uint256>;
  getVoiceCreditAmount: () => Promise<Uint256>;
  signuped: ({
    pubkey
  }: {
    pubkey: PubKey;
  }) => Promise<NullableUint256>;
  voteOptionMap: () => Promise<ArrayOfString>;
  maxVoteOptions: () => Promise<Uint256>;
  queryCircuitType: () => Promise<Uint256>;
  queryCertSystem: () => Promise<Uint256>;
  queryPreDeactivateRoot: () => Promise<Uint256>;
  queryPreDeactivateCoordinatorHash: () => Promise<NullableUint256>;
  getDelayRecords: () => Promise<DelayRecords>;
  getTallyDelay: () => Promise<TallyDelayInfo>;
  queryOracleWhitelistConfig: () => Promise<NullableString>;
  queryCurrentStateCommitment: () => Promise<Uint256>;
  getCoordinatorHash: () => Promise<Uint256>;
  getMsgHash: ({
    index
  }: {
    index: Uint256;
  }) => Promise<Uint256>;
  getCurrentDeactivateCommitment: () => Promise<Uint256>;
  getPollId: () => Promise<Uint64>;
  getDeactivateEnabled: () => Promise<Boolean>;
  getRegistrationConfig: () => Promise<RegistrationConfigInfo>;
  queryRegistrationStatus: ({
    amount,
    certificate,
    pubkey,
    sender
  }: {
    amount?: Uint256;
    certificate?: string;
    pubkey?: PubKey;
    sender?: Addr;
  }) => Promise<RegistrationStatus>;
  getFeeConfig: () => Promise<FeeConfigResponse>;
  getDelayConfig: () => Promise<DelayConfigResponse>;
}
export class AMaciQueryClient implements AMaciReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.admin = this.admin.bind(this);
    this.operator = this.operator.bind(this);
    this.getRoundInfo = this.getRoundInfo.bind(this);
    this.getVotingTime = this.getVotingTime.bind(this);
    this.getPeriod = this.getPeriod.bind(this);
    this.getNumSignUp = this.getNumSignUp.bind(this);
    this.getMsgChainLength = this.getMsgChainLength.bind(this);
    this.getDMsgChainLength = this.getDMsgChainLength.bind(this);
    this.getProcessedDMsgCount = this.getProcessedDMsgCount.bind(this);
    this.getProcessedMsgCount = this.getProcessedMsgCount.bind(this);
    this.getProcessedUserCount = this.getProcessedUserCount.bind(this);
    this.getStateTreeRoot = this.getStateTreeRoot.bind(this);
    this.getNode = this.getNode.bind(this);
    this.getResult = this.getResult.bind(this);
    this.getAllResult = this.getAllResult.bind(this);
    this.getAllResults = this.getAllResults.bind(this);
    this.getStateIdxInc = this.getStateIdxInc.bind(this);
    this.getVoiceCreditBalance = this.getVoiceCreditBalance.bind(this);
    this.getVoiceCreditAmount = this.getVoiceCreditAmount.bind(this);
    this.signuped = this.signuped.bind(this);
    this.voteOptionMap = this.voteOptionMap.bind(this);
    this.maxVoteOptions = this.maxVoteOptions.bind(this);
    this.queryCircuitType = this.queryCircuitType.bind(this);
    this.queryCertSystem = this.queryCertSystem.bind(this);
    this.queryPreDeactivateRoot = this.queryPreDeactivateRoot.bind(this);
    this.queryPreDeactivateCoordinatorHash = this.queryPreDeactivateCoordinatorHash.bind(this);
    this.getDelayRecords = this.getDelayRecords.bind(this);
    this.getTallyDelay = this.getTallyDelay.bind(this);
    this.queryOracleWhitelistConfig = this.queryOracleWhitelistConfig.bind(this);
    this.queryCurrentStateCommitment = this.queryCurrentStateCommitment.bind(this);
    this.getCoordinatorHash = this.getCoordinatorHash.bind(this);
    this.getMsgHash = this.getMsgHash.bind(this);
    this.getCurrentDeactivateCommitment = this.getCurrentDeactivateCommitment.bind(this);
    this.getPollId = this.getPollId.bind(this);
    this.getDeactivateEnabled = this.getDeactivateEnabled.bind(this);
    this.getRegistrationConfig = this.getRegistrationConfig.bind(this);
    this.queryRegistrationStatus = this.queryRegistrationStatus.bind(this);
    this.getFeeConfig = this.getFeeConfig.bind(this);
    this.getDelayConfig = this.getDelayConfig.bind(this);
  }
  admin = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin: {}
    });
  };
  operator = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operator: {}
    });
  };
  getRoundInfo = async (): Promise<RoundInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_round_info: {}
    });
  };
  getVotingTime = async (): Promise<VotingTime> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_voting_time: {}
    });
  };
  getPeriod = async (): Promise<Period> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_period: {}
    });
  };
  getNumSignUp = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_num_sign_up: {}
    });
  };
  getMsgChainLength = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_msg_chain_length: {}
    });
  };
  getDMsgChainLength = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_d_msg_chain_length: {}
    });
  };
  getProcessedDMsgCount = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_processed_d_msg_count: {}
    });
  };
  getProcessedMsgCount = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_processed_msg_count: {}
    });
  };
  getProcessedUserCount = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_processed_user_count: {}
    });
  };
  getStateTreeRoot = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_state_tree_root: {}
    });
  };
  getNode = async ({
    index
  }: {
    index: Uint256;
  }): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_node: {
        index
      }
    });
  };
  getResult = async ({
    index
  }: {
    index: Uint256;
  }): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_result: {
        index
      }
    });
  };
  getAllResult = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_result: {}
    });
  };
  getAllResults = async (): Promise<ArrayOfUint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_results: {}
    });
  };
  getStateIdxInc = async ({
    address
  }: {
    address: Addr;
  }): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_state_idx_inc: {
        address
      }
    });
  };
  getVoiceCreditBalance = async ({
    index
  }: {
    index: Uint256;
  }): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_voice_credit_balance: {
        index
      }
    });
  };
  getVoiceCreditAmount = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_voice_credit_amount: {}
    });
  };
  signuped = async ({
    pubkey
  }: {
    pubkey: PubKey;
  }): Promise<NullableUint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      signuped: {
        pubkey
      }
    });
  };
  voteOptionMap = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vote_option_map: {}
    });
  };
  maxVoteOptions = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      max_vote_options: {}
    });
  };
  queryCircuitType = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_circuit_type: {}
    });
  };
  queryCertSystem = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_cert_system: {}
    });
  };
  queryPreDeactivateRoot = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_pre_deactivate_root: {}
    });
  };
  queryPreDeactivateCoordinatorHash = async (): Promise<NullableUint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_pre_deactivate_coordinator_hash: {}
    });
  };
  getDelayRecords = async (): Promise<DelayRecords> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_delay_records: {}
    });
  };
  getTallyDelay = async (): Promise<TallyDelayInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_tally_delay: {}
    });
  };
  queryOracleWhitelistConfig = async (): Promise<NullableString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_oracle_whitelist_config: {}
    });
  };
  queryCurrentStateCommitment = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_current_state_commitment: {}
    });
  };
  getCoordinatorHash = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_coordinator_hash: {}
    });
  };
  getMsgHash = async ({
    index
  }: {
    index: Uint256;
  }): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_msg_hash: {
        index
      }
    });
  };
  getCurrentDeactivateCommitment = async (): Promise<Uint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_current_deactivate_commitment: {}
    });
  };
  getPollId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_poll_id: {}
    });
  };
  getDeactivateEnabled = async (): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_deactivate_enabled: {}
    });
  };
  getRegistrationConfig = async (): Promise<RegistrationConfigInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_registration_config: {}
    });
  };
  queryRegistrationStatus = async ({
    amount,
    certificate,
    pubkey,
    sender
  }: {
    amount?: Uint256;
    certificate?: string;
    pubkey?: PubKey;
    sender?: Addr;
  }): Promise<RegistrationStatus> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_registration_status: {
        amount,
        certificate,
        pubkey,
        sender
      }
    });
  };
  getFeeConfig = async (): Promise<FeeConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_fee_config: {}
    });
  };
  getDelayConfig = async (): Promise<DelayConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_delay_config: {}
    });
  };
}
export interface AMaciInterface extends AMaciReadOnlyInterface {
  contractAddress: string;
  sender: string;
  setRoundInfo: ({
    roundInfo
  }: {
    roundInfo: RoundInfo;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateRegistrationConfig: ({
    config
  }: {
    config: RegistrationConfigUpdate;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setVoteOptionsMap: ({
    voteOptionMap
  }: {
    voteOptionMap: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  signUp: ({
    amount,
    certificate,
    pubkey
  }: {
    amount?: Uint256;
    certificate?: string;
    pubkey: PubKey;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  startProcessPeriod: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  publishDeactivateMessage: ({
    encPubKey,
    message
  }: {
    encPubKey: PubKey;
    message: MessageData;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  processDeactivateMessage: ({
    groth16Proof,
    newDeactivateCommitment,
    newDeactivateRoot,
    size
  }: {
    groth16Proof: Groth16ProofType;
    newDeactivateCommitment: Uint256;
    newDeactivateRoot: Uint256;
    size: Uint256;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addNewKey: ({
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    d: Uint256[];
    groth16Proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  preAddNewKey: ({
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    d: Uint256[];
    groth16Proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  publishMessage: ({
    encPubKeys,
    messages
  }: {
    encPubKeys: PubKey[];
    messages: MessageData[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  processMessage: ({
    groth16Proof,
    newStateCommitment
  }: {
    groth16Proof: Groth16ProofType;
    newStateCommitment: Uint256;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  stopProcessingPeriod: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  processTally: ({
    groth16Proof,
    newTallyCommitment
  }: {
    groth16Proof: Groth16ProofType;
    newTallyCommitment: Uint256;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  stopTallyingPeriod: ({
    results,
    salt
  }: {
    results: Uint256[];
    salt: Uint256;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claim: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class AMaciClient extends AMaciQueryClient implements AMaciInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setRoundInfo = this.setRoundInfo.bind(this);
    this.updateRegistrationConfig = this.updateRegistrationConfig.bind(this);
    this.setVoteOptionsMap = this.setVoteOptionsMap.bind(this);
    this.signUp = this.signUp.bind(this);
    this.startProcessPeriod = this.startProcessPeriod.bind(this);
    this.publishDeactivateMessage = this.publishDeactivateMessage.bind(this);
    this.processDeactivateMessage = this.processDeactivateMessage.bind(this);
    this.addNewKey = this.addNewKey.bind(this);
    this.preAddNewKey = this.preAddNewKey.bind(this);
    this.publishMessage = this.publishMessage.bind(this);
    this.processMessage = this.processMessage.bind(this);
    this.stopProcessingPeriod = this.stopProcessingPeriod.bind(this);
    this.processTally = this.processTally.bind(this);
    this.stopTallyingPeriod = this.stopTallyingPeriod.bind(this);
    this.claim = this.claim.bind(this);
  }
  setRoundInfo = async ({
    roundInfo
  }: {
    roundInfo: RoundInfo;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_round_info: {
        round_info: roundInfo
      }
    }, fee, memo, _funds);
  };
  updateRegistrationConfig = async ({
    config
  }: {
    config: RegistrationConfigUpdate;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_registration_config: {
        config
      }
    }, fee, memo, _funds);
  };
  setVoteOptionsMap = async ({
    voteOptionMap
  }: {
    voteOptionMap: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_vote_options_map: {
        vote_option_map: voteOptionMap
      }
    }, fee, memo, _funds);
  };
  signUp = async ({
    amount,
    certificate,
    pubkey
  }: {
    amount?: Uint256;
    certificate?: string;
    pubkey: PubKey;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      sign_up: {
        amount,
        certificate,
        pubkey
      }
    }, fee, memo, _funds);
  };
  startProcessPeriod = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      start_process_period: {}
    }, fee, memo, _funds);
  };
  publishDeactivateMessage = async ({
    encPubKey,
    message
  }: {
    encPubKey: PubKey;
    message: MessageData;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      publish_deactivate_message: {
        enc_pub_key: encPubKey,
        message
      }
    }, fee, memo, _funds);
  };
  processDeactivateMessage = async ({
    groth16Proof,
    newDeactivateCommitment,
    newDeactivateRoot,
    size
  }: {
    groth16Proof: Groth16ProofType;
    newDeactivateCommitment: Uint256;
    newDeactivateRoot: Uint256;
    size: Uint256;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      process_deactivate_message: {
        groth16_proof: groth16Proof,
        new_deactivate_commitment: newDeactivateCommitment,
        new_deactivate_root: newDeactivateRoot,
        size
      }
    }, fee, memo, _funds);
  };
  addNewKey = async ({
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    d: Uint256[];
    groth16Proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_new_key: {
        d,
        groth16_proof: groth16Proof,
        nullifier,
        pubkey
      }
    }, fee, memo, _funds);
  };
  preAddNewKey = async ({
    d,
    groth16Proof,
    nullifier,
    pubkey
  }: {
    d: Uint256[];
    groth16Proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pre_add_new_key: {
        d,
        groth16_proof: groth16Proof,
        nullifier,
        pubkey
      }
    }, fee, memo, _funds);
  };
  publishMessage = async ({
    encPubKeys,
    messages
  }: {
    encPubKeys: PubKey[];
    messages: MessageData[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      publish_message: {
        enc_pub_keys: encPubKeys,
        messages
      }
    }, fee, memo, _funds);
  };
  processMessage = async ({
    groth16Proof,
    newStateCommitment
  }: {
    groth16Proof: Groth16ProofType;
    newStateCommitment: Uint256;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      process_message: {
        groth16_proof: groth16Proof,
        new_state_commitment: newStateCommitment
      }
    }, fee, memo, _funds);
  };
  stopProcessingPeriod = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      stop_processing_period: {}
    }, fee, memo, _funds);
  };
  processTally = async ({
    groth16Proof,
    newTallyCommitment
  }: {
    groth16Proof: Groth16ProofType;
    newTallyCommitment: Uint256;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      process_tally: {
        groth16_proof: groth16Proof,
        new_tally_commitment: newTallyCommitment
      }
    }, fee, memo, _funds);
  };
  stopTallyingPeriod = async ({
    results,
    salt
  }: {
    results: Uint256[];
    salt: Uint256;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      stop_tallying_period: {
        results,
        salt
      }
    }, fee, memo, _funds);
  };
  claim = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {}
    }, fee, memo, _funds);
  };
}