/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint256 = string;
export type Uint128 = string;
export type RegistrationModeConfig = {
  sign_up_with_static_whitelist: {
    whitelist: WhitelistBase;
  };
} | {
  sign_up_with_oracle: {
    oracle_pubkey: string;
  };
} | {
  pre_populated: {
    pre_deactivate_coordinator: PubKey;
    pre_deactivate_root: Uint256;
  };
};
export type VoiceCreditMode = "dynamic" | {
  unified: {
    amount: Uint256;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
  admin: Addr;
  base_delay: number;
  certification_system: Uint256;
  circuit_type: Uint256;
  coordinator: PubKey;
  deactivate_delay: number;
  deactivate_enabled: boolean;
  deactivate_fee: Uint128;
  fee_recipient: Addr;
  message_delay: number;
  message_fee: Uint128;
  operator: Addr;
  parameters: MaciParameters;
  poll_id: number;
  registration_mode: RegistrationModeConfig;
  round_info: RoundInfo;
  signup_delay: number;
  signup_fee: Uint128;
  voice_credit_mode: VoiceCreditMode;
  vote_option_map: string[];
  voting_time: VotingTime;
}
export interface PubKey {
  x: Uint256;
  y: Uint256;
}
export interface MaciParameters {
  int_state_tree_depth: Uint256;
  message_batch_size: Uint256;
  state_tree_depth: Uint256;
  vote_option_tree_depth: Uint256;
}
export interface WhitelistBase {
  users: WhitelistBaseConfig[];
}
export interface WhitelistBaseConfig {
  addr: Addr;
  voice_credit_amount?: Uint256 | null;
}
export interface RoundInfo {
  description: string;
  link: string;
  title: string;
}
export interface VotingTime {
  end_time: Timestamp;
  start_time: Timestamp;
}
export type ExecuteMsg = {
  set_round_info: {
    round_info: RoundInfo;
  };
} | {
  update_registration_config: {
    config: RegistrationConfigUpdate;
  };
} | {
  set_vote_options_map: {
    vote_option_map: string[];
  };
} | {
  sign_up: {
    amount?: Uint256 | null;
    certificate?: string | null;
    pubkey: PubKey;
  };
} | {
  start_process_period: {};
} | {
  publish_deactivate_message: {
    enc_pub_key: PubKey;
    message: MessageData;
  };
} | {
  process_deactivate_message: {
    groth16_proof: Groth16ProofType;
    new_deactivate_commitment: Uint256;
    new_deactivate_root: Uint256;
    size: Uint256;
  };
} | {
  add_new_key: {
    d: [Uint256, Uint256, Uint256, Uint256];
    groth16_proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  };
} | {
  pre_add_new_key: {
    d: [Uint256, Uint256, Uint256, Uint256];
    groth16_proof: Groth16ProofType;
    nullifier: Uint256;
    pubkey: PubKey;
  };
} | {
  publish_message: {
    enc_pub_keys: PubKey[];
    messages: MessageData[];
  };
} | {
  process_message: {
    groth16_proof: Groth16ProofType;
    new_state_commitment: Uint256;
  };
} | {
  stop_processing_period: {};
} | {
  process_tally: {
    groth16_proof: Groth16ProofType;
    new_tally_commitment: Uint256;
  };
} | {
  stop_tallying_period: {
    results: Uint256[];
    salt: Uint256;
  };
} | {
  claim: {};
};
export interface RegistrationConfigUpdate {
  deactivate_enabled?: boolean | null;
  registration_mode?: RegistrationModeConfig | null;
  voice_credit_mode?: VoiceCreditMode | null;
}
export interface MessageData {
  data: [Uint256, Uint256, Uint256, Uint256, Uint256, Uint256, Uint256, Uint256, Uint256, Uint256];
}
export interface Groth16ProofType {
  a: string;
  b: string;
  c: string;
}
export type QueryMsg = {
  admin: {};
} | {
  operator: {};
} | {
  get_round_info: {};
} | {
  get_voting_time: {};
} | {
  get_period: {};
} | {
  get_num_sign_up: {};
} | {
  get_msg_chain_length: {};
} | {
  get_d_msg_chain_length: {};
} | {
  get_processed_d_msg_count: {};
} | {
  get_processed_msg_count: {};
} | {
  get_processed_user_count: {};
} | {
  get_state_tree_root: {};
} | {
  get_node: {
    index: Uint256;
  };
} | {
  get_result: {
    index: Uint256;
  };
} | {
  get_all_result: {};
} | {
  get_all_results: {};
} | {
  get_state_idx_inc: {
    address: Addr;
  };
} | {
  get_voice_credit_balance: {
    index: Uint256;
  };
} | {
  get_voice_credit_amount: {};
} | {
  signuped: {
    pubkey: PubKey;
  };
} | {
  vote_option_map: {};
} | {
  max_vote_options: {};
} | {
  query_circuit_type: {};
} | {
  query_cert_system: {};
} | {
  query_pre_deactivate_root: {};
} | {
  query_pre_deactivate_coordinator_hash: {};
} | {
  get_delay_records: {};
} | {
  get_tally_delay: {};
} | {
  query_oracle_whitelist_config: {};
} | {
  query_current_state_commitment: {};
} | {
  get_coordinator_hash: {};
} | {
  get_msg_hash: {
    index: Uint256;
  };
} | {
  get_current_deactivate_commitment: {};
} | {
  get_poll_id: {};
} | {
  get_deactivate_enabled: {};
} | {
  get_registration_config: {};
} | {
  query_registration_status: {
    amount?: Uint256 | null;
    certificate?: string | null;
    pubkey?: PubKey | null;
    sender?: Addr | null;
  };
} | {
  get_message_fee: {};
} | {
  get_deactivate_fee: {};
} | {
  get_signup_fee: {};
} | {
  get_base_delay: {};
} | {
  get_message_delay: {};
} | {
  get_signup_delay: {};
} | {
  get_deactivate_delay: {};
};
export type ArrayOfUint256 = Uint256[];
export type Boolean = boolean;
export type DelayType = "deactivate_delay" | "tally_delay";
export interface DelayRecords {
  records: DelayRecord[];
}
export interface DelayRecord {
  delay_duration: number;
  delay_process_dmsg_count: Uint256;
  delay_reason: string;
  delay_timestamp: Timestamp;
  delay_type: DelayType;
}
export type PeriodStatus = "pending" | "processing" | "tallying" | "ended";
export interface Period {
  status: PeriodStatus;
}
export type RegistrationMode = "sign_up_with_static_whitelist" | {
  sign_up_with_oracle: {
    oracle_pubkey: string;
  };
} | {
  pre_populated: {
    pre_deactivate_coordinator: PubKey;
    pre_deactivate_root: Uint256;
  };
};
export interface RegistrationConfigInfo {
  deactivate_enabled: boolean;
  registration_mode: RegistrationMode;
  voice_credit_mode: VoiceCreditMode;
}
export interface TallyDelayInfo {
  calculated_hours: number;
  delay_seconds: number;
  msg_chain_length: Uint256;
  num_sign_ups: Uint256;
  total_work: number;
}
export type NullableString = string | null;
export type NullableUint256 = Uint256 | null;
export interface RegistrationStatus {
  balance: Uint256;
  can_sign_up: boolean;
  is_register: boolean;
}
export type ArrayOfString = string[];